-- =============================================================================
-- GRIMOIRE COLLECTIVE - CRYSTAL DATA
-- =============================================================================
-- Purpose: Comprehensive crystal/stone data for the knowledge base
-- Note: This is permanent data, not sample data
-- =============================================================================

DO $$
DECLARE
    admin_user_id UUID;
BEGIN
    SELECT id INTO admin_user_id FROM users WHERE username = 'admin' LIMIT 1;

INSERT INTO crystals (
    name, slug, alternative_names, color, chakra, zodiac_signs, element, planet,
    magical_properties, cleansing_methods, charging_methods,
    description, uses, water_safe, sun_safe, salt_safe, rarity,
    history, directions, storage_instructions, safety_warnings,
    created_by, is_verified
) VALUES
(
    'Clear Quartz',
    'clear-quartz',
    ARRAY['Rock Crystal', 'Crystal Quartz'],
    'Clear/White',
    'Crown',
    ARRAY['All'],
    'All',
    'Sun',
    ARRAY['amplification', 'clarity', 'healing', 'energy', 'manifestation', 'meditation'],
    ARRAY['full_moon', 'running_water', 'smoke', 'sound'],
    ARRAY['moonlight', 'sunlight', 'crystal_cluster'],
    'Clear Quartz is known as the "Master Healer" and "Universal Crystal". It is the most versatile healing stone among all crystals. It has the ability to amplify energy and thought, as well as the effect of other crystals.',
    'Use Clear Quartz in meditation to amplify intentions, place on any chakra for healing, program it for specific purposes, use in crystal grids as a central stone or amplifier.',
    true,
    true,
    true,
    'common',
    'Clear Quartz has been revered since ancient times across nearly every culture. The name "quartz" comes from the Greek word "krystallos" meaning ice, as ancient Greeks believed it was water frozen so solid it would never thaw. Ancient Roman, Egyptian, and Greek civilizations used clear quartz in jewelry and carvings. In Asia, crystal balls made from clear quartz were used for divination. Native Americans used it in sacred ceremonies. The Japanese called it "the perfect jewel" believing it symbolized infinite space, purity, and perseverance. It has been used in healing and spiritual practices for over 6,000 years.',
    'To use Clear Quartz: Hold in your hand or place on body during meditation. Program by holding and focusing your intention into the stone. Use in crystal grids as a master stone or amplifier. Place on altar to amplify magical workings. Wear as jewelry for constant energetic support. Place in corners of room for space clearing. Combine with other stones to amplify their properties. Cleanse regularly as it absorbs energy easily.',
    'Store in soft cloth or padded box to prevent scratches. Can be stored with other stones. Keep away from harsh chemicals and extreme temperature changes. Safe to store in sunlight and moonlight.',
    'Clear Quartz is safe to handle and wear. Water safe. Sun safe. Salt safe. Non-toxic. Points can be sharp - handle carefully to avoid cuts.',
    admin_user_id,
    true
),
(
    'Rose Quartz',
    'rose-quartz',
    ARRAY['Pink Quartz', 'Love Stone'],
    'Pink',
    'Heart',
    ARRAY['Taurus', 'Libra'],
    'Water',
    'Venus',
    ARRAY['love', 'compassion', 'emotional_healing', 'self_love', 'relationships', 'peace'],
    ARRAY['full_moon', 'running_water', 'smoke'],
    ARRAY['moonlight', 'earth'],
    'Rose Quartz is the stone of universal love. It restores trust and harmony in relationships, encouraging unconditional love. Rose Quartz purifies and opens the heart at all levels to promote love, self-love, friendship, deep inner healing and feelings of peace.',
    'Place Rose Quartz in your bedroom to attract love, hold during meditation for self-love work, wear as jewelry near your heart, use in love spells and attraction rituals.',
    true,
    false,
    true,
    'common',
    'Rose Quartz has been used as a love token since 600 B.C. Ancient Assyrians and Romans were among the first to use rose quartz in jewelry and amulets. In Egyptian and Roman mythology, rose quartz was believed to be a gift from Cupid and Eros to inspire love among people. It was also used in facial masks by Egyptian and Roman women to beautify their complexion. Ancient Tibetan and Chinese cultures carved healing amulets from rose quartz. Greek mythology says Aphrodite''s blood stained clear quartz pink when she tried to save Adonis, creating rose quartz.',
    'To use Rose Quartz: Place over heart chakra during meditation for self-love and healing. Keep near bed to attract love and promote peaceful sleep. Carry in pocket or wear as jewelry to stay open to love throughout the day. Create a love altar with rose quartz as the centerpiece. Use in bath water for self-love rituals (water safe). Place in relationship corner of home (far right corner from entrance) for feng shui love energy. Give as gifts to loved ones.',
    'Store away from direct sunlight as prolonged sun exposure may fade the pink color. Keep in soft cloth to prevent scratches. Can be stored with other gentle stones. Room temperature storage is ideal.',
    'Rose Quartz is safe to handle and wear. Water safe. Salt safe. NOT sun safe - will fade in direct sunlight over time. Non-toxic. Generally gentle energy suitable for everyone including children.',
    admin_user_id,
    true
),
(
    'Amethyst',
    'amethyst',
    ARRAY['Purple Quartz', 'Bishop Stone'],
    'Purple',
    'Third Eye',
    ARRAY['Pisces', 'Virgo', 'Aquarius', 'Capricorn'],
    'Air',
    'Jupiter',
    ARRAY['spirituality', 'intuition', 'protection', 'purification', 'wisdom', 'sobriety'],
    ARRAY['full_moon', 'smoke', 'sound'],
    ARRAY['moonlight', 'crystal_cluster'],
    'Amethyst is a powerful and protective stone. It guards against psychic attack, transmuting the energy into love and protecting the wearer from all types of harm. Amethyst is a natural tranquilizer, it relieves stress and strain, soothes irritability, balances mood swings, and dispels anger, rage, fear and anxiety.',
    'Place Amethyst on your third eye during meditation, keep by bedside to prevent nightmares, use in divination and psychic work, carry for protection, place in your home to maintain peaceful energy.',
    true,
    false,
    true,
    'common',
    'Amethyst''s name comes from the Greek "amethystos" meaning "not intoxicated," as ancient Greeks believed it protected against drunkenness. They carved drinking vessels from amethyst to prevent intoxication. Leonardo da Vinci wrote that amethyst could dissipate evil thoughts and quicken intelligence. In medieval times, European soldiers wore amethyst amulets for protection in battle. It has been a stone of royalty, adorning the British Crown Jewels and worn by Catholic bishops. Ancient Egyptians used it in amulets and jewelry. Tibetan Buddhists make prayer beads from amethyst.',
    'To use Amethyst: Place on third eye chakra during meditation to enhance intuition. Keep by bedside or under pillow to prevent nightmares and promote restful sleep. Hold during meditation to connect with higher consciousness. Place in workspace to enhance mental clarity and creativity. Create a meditation grid with amethyst at center. Wear as jewelry for spiritual protection throughout the day. Place in home to maintain peaceful, protective energy. Use in moon rituals and spiritual ceremonies.',
    'Store away from direct sunlight as amethyst will fade to pale lavender or clear if exposed to strong sun for prolonged periods. Keep in padded box or soft cloth. Room temperature storage is best.',
    'Amethyst is safe to handle and wear. Water safe. Salt safe. NOT sun safe - will fade in sunlight. Non-toxic. Safe for all ages. The calming energy makes it excellent for beginners and children.',
    admin_user_id,
    true
),
(
    'Black Tourmaline',
    'black-tourmaline',
    ARRAY['Schorl', 'Black Schorl'],
    'Black',
    'Root',
    ARRAY['Capricorn'],
    'Earth',
    'Saturn',
    ARRAY['protection', 'grounding', 'purification', 'shielding', 'EMF_protection', 'dispels_negativity'],
    ARRAY['full_moon', 'running_water', 'smoke', 'sound', 'earth'],
    ARRAY['moonlight', 'sunlight', 'earth'],
    'Black Tourmaline is a powerful grounding stone, providing a connection between Earth and the human spirit. It provides protection from negative energies and electromagnetic radiation. Black Tourmaline also helps to balance and align the chakras.',
    'Place Black Tourmaline at the four corners of your home for protection, carry it for personal shielding, place near electronics to absorb EMF, use in grounding meditation, keep by the front door.',
    true,
    true,
    true,
    'common',
    'Black Tourmaline has been used for protection since ancient times. Dutch traders in the 1700s brought it to Europe from Sri Lanka, where they observed its pyroelectric properties (becomes electrically charged when heated). Ancient magicians relied upon Black Tourmaline to protect them from earth demons. The name tourmaline comes from the Sinhalese word "turamali" meaning "stone with mixed colors," though black tourmaline (schorl) is the most common variety. Indigenous peoples used it in shamanic practices. In the 1800s, it was used in scientific instruments due to its electrical properties.',
    'To use Black Tourmaline: Place at the four corners of your home for protection. Keep by front door to prevent negative energy from entering. Place near computer or electronic devices to absorb electromagnetic frequencies (EMF). Carry in pocket or wear as jewelry for personal protection throughout the day. Place under pillow to protect against nightmares. Use in grounding meditation by holding or placing at feet. Create protective grids with black tourmaline. Place in car for travel protection.',
    'Store in any container. Black Tourmaline is very hardy. Can be stored with other protective stones. Safe in sunlight, moonlight, water, and salt. Cleanse frequently as it absorbs negative energy.',
    'Black Tourmaline is safe to handle and wear. Water safe. Sun safe. Salt safe. Non-toxic. Extremely safe and grounding. One of the safest protection stones for everyone including children and pets nearby.',
    admin_user_id,
    true
),
(
    'Citrine',
    'citrine',
    ARRAY['Success Stone', 'Merchant Stone'],
    'Yellow to Golden',
    'Solar Plexus',
    ARRAY['Aries', 'Gemini', 'Leo', 'Libra'],
    'Fire',
    'Sun',
    ARRAY['abundance', 'manifestation', 'prosperity', 'success', 'confidence', 'joy'],
    ARRAY['running_water', 'smoke', 'sound'],
    ARRAY['sunlight', 'crystal_cluster'],
    'Citrine is a stone of abundance and manifestation. It carries the power of the sun and is energizing and life-giving. It never needs cleansing as it does not hold negative energy. Citrine attracts wealth, prosperity, and success.',
    'Place Citrine in your cash register or wallet, use in manifestation rituals, keep in the wealth corner of your home (far left from entrance), carry for confidence and personal power.',
    true,
    true,
    true,
    'common',
    'Citrine''s name comes from the French word "citron" meaning lemon. Natural citrine is rare; most citrine available today is heat-treated amethyst or smoky quartz. The ancient Greeks carved citrine into rock crystal as early as 300 B.C. Roman priests wore citrine rings. Citrine was popular in Art Deco jewelry in the 1930s. Ancient cultures believed citrine carried the power of the sun. Merchants carried citrine in their cash boxes or registers to attract wealth and prosperity, earning it the nickname "merchant''s stone." Scottish warriors used citrine on weapon handles for protection.',
    'To use Citrine: Place in cash register, wallet, or wealth corner of home (far left from entrance) to attract abundance. Hold during manifestation meditations focusing on goals and prosperity. Wear as jewelry to maintain positive, abundant energy throughout the day. Place on solar plexus chakra to boost confidence and personal power. Keep in workspace to attract success and maintain motivation. Use in sun rituals and prosperity spells. Create abundance grids with citrine as focal point. Never needs cleansing as it doesn''t hold negative energy.',
    'Store in a sunny window if desired - citrine loves sunlight. Can be stored anywhere safely. Does not need protective cloth as it''s quite hard. Can be stored with other stones. Does not need frequent cleansing as it is self-cleansing.',
    'Citrine is safe to handle and wear. Water safe. Sun safe (will not fade). Salt safe. Non-toxic. Very safe stone with positive, uplifting energy. Suitable for everyone. Note: Most citrine is heat-treated amethyst, not natural citrine, but properties remain the same.',
    admin_user_id,
    true
),
(
    'Labradorite',
    'labradorite',
    ARRAY['Spectrolite', 'Rainbow Moonstone (misnamed)'],
    'Gray with iridescent flashes',
    'Third Eye',
    ARRAY['Leo', 'Scorpio', 'Sagittarius'],
    'Water',
    'Uranus',
    ARRAY['transformation', 'intuition', 'protection', 'magic', 'psychic_abilities', 'strength'],
    ARRAY['full_moon', 'smoke', 'sound'],
    ARRAY['moonlight', 'crystal_cluster'],
    'Labradorite is a stone of transformation and magic. It enhances intuition, psychic abilities, and connection to the spiritual realm. Labradorite creates a protective shield around the aura, preventing energy leakage and protecting against negative energies.',
    'Use Labradorite in meditation to enhance psychic abilities, carry for protection from negative energy, use during transformation work, place on third eye chakra during spiritual work.',
    true,
    false,
    false,
    'uncommon',
    'Labradorite was first discovered in Labrador, Canada in 1770, though Inuit peoples have known of it for centuries and have legends about it. According to Inuit legend, the Northern Lights were once trapped in rocks along the coast of Labrador. A warrior struck the rocks with his spear, freeing most of the lights into the sky, but some remained trapped in the stone - this became labradorite. It has been used by shamans and mystics throughout history for its protective and mystical properties. Finnish folklore speaks of similar stone with mystical light.',
    'To use Labradorite: Hold during meditation to access higher realms and enhance psychic abilities. Place on third eye chakra to awaken intuition and inner sight. Carry when you need protection from negative energies and energy vampires. Wear as jewelry to maintain auric shield throughout the day. Use in transformation and shadow work rituals. Place in workspace to protect against negative workplace energies. Keep near electronics to reduce EMF exposure. Use during dark moon rituals and magic work.',
    'Store away from direct sunlight to preserve its flash (labradorescence). Keep in soft cloth or padded box as it has perfect cleavage and can break along those planes if dropped. Store with other mystical stones if desired. Room temperature storage recommended.',
    'Labradorite is safe to handle and wear. Water safe (but don''t submerge for extended periods). NOT sun safe - prolonged sun exposure may reduce the flash/iridescence. Not ideal for salt cleansing due to cleavage planes. Non-toxic. Can be delicate due to perfect cleavage - handle with care to avoid dropping.',
    admin_user_id,
    true
),
(
    'Selenite',
    'selenite',
    ARRAY['Satin Spar', 'Gypsum'],
    'White/Clear',
    'Crown',
    ARRAY['Taurus', 'Cancer'],
    'Spirit',
    'Moon',
    ARRAY['cleansing', 'clarity', 'peace', 'higher_consciousness', 'angelic_connection', 'charging'],
    ARRAY['sound', 'smoke', 'moonlight'],
    ARRAY['moonlight', 'self_cleansing'],
    'Selenite is a calming stone that instills deep peace and is excellent for meditation or spiritual work. It has the unique property of being able to cleanse and charge other crystals. Selenite connects to higher consciousness and facilitates angelic communication.',
    'Use Selenite to cleanse other crystals, place in corners of home for high vibration, use wands to cleanse your aura, meditate with selenite for spiritual connection, place on crown chakra.',
    false,
    true,
    false,
    'common',
    'Selenite is named after Selene, the Greek goddess of the moon, because of its moon-like glow. Ancient Greeks believed it increased and decreased with the moon. Large selenite crystals have been found in the Cave of Crystals in Naica, Mexico - some of the largest crystals ever discovered. Mesopotamians used selenite in their architecture and decoration. It has been used for thousands of years in spiritual practices. Ancient civilizations carved selenite into windows and decorative pieces. It was believed to bring mental clarity and clear thinking.',
    'To use Selenite: Use to cleanse and charge other crystals - place them on a selenite charging plate or wand. Hold during meditation for mental clarity and connection to higher consciousness. Place in corners of room to maintain high vibration and clear energy. Use wands to sweep aura clean. Place on crown chakra to open spiritual connection. Create crystal grids with selenite as the connecting energy. Keep by bedside for peaceful sleep and angelic connection. Use to cleanse sacred space before ritual or ceremony.',
    'NEVER store in water or humid environments as selenite is water-soluble and will deteriorate. Store in dry location in soft cloth or box. Keep away from moisture and humidity. Do not store in bathroom or other damp areas. Handle gently as it is soft and can scratch easily.',
    'Selenite is safe to handle. NOT water safe - will dissolve in water. Sun safe. NOT salt safe. Non-toxic but do not ingest. Very soft (2 on Mohs scale) and can flake - be gentle. Wands can have sharp edges. Never cleanse in water - use smoke, sound, or moonlight only. Keep away from moisture and humidity. Can be brittle and break if dropped.',
    admin_user_id,
    true
),
(
    'Carnelian',
    'carnelian',
    ARRAY['Cornelian', 'Red Chalcedony'],
    'Orange to Red',
    'Sacral',
    ARRAY['Taurus', 'Cancer', 'Leo', 'Virgo'],
    'Fire',
    'Sun',
    ARRAY['motivation', 'courage', 'creativity', 'vitality', 'confidence', 'action'],
    ARRAY['full_moon', 'running_water', 'smoke', 'sound'],
    ARRAY['sunlight', 'moonlight'],
    'Carnelian is a stone of motivation, endurance, and courage. It stimulates creativity and promotes positive life choices. Carnelian restores vitality and motivation, and stimulates creativity. It gives courage, promotes positive life choices, and dispels apathy.',
    'Carry Carnelian for courage and motivation, place on sacral chakra during meditation, use in creativity rituals, wear as jewelry for confidence, place in creative workspace.',
    true,
    true,
    true,
    'common',
    'Carnelian has been used since ancient times, dating back over 4,000 years. Ancient Egyptians called carnelian "the setting sun" and associated it with the goddess Isis. It was worn by Egyptian nobility and used to protect the dead on their journey to the afterlife. The Egyptians also buried carnelian scarabs with mummies. The prophet Muhammad wore a carnelian ring. Ancient Romans used carnelian for signet rings as hot wax wouldn''t stick to it. Warriors wore carnelian for courage and physical power. Napoleon found a carnelian scarab in Egypt and wore it throughout his life.',
    'To use Carnelian: Place on sacral chakra during meditation to boost creativity and passion. Carry when you need motivation, courage, or confidence. Wear as jewelry to maintain vitality and positive energy throughout the day. Place in creative workspace to overcome creative blocks. Use in passion and creativity rituals. Hold during manifestation work to add energy and motivation to intentions. Place near front door to invite abundance and positive energy into home. Use in fire magic and rituals.',
    'Store in any safe container. Carnelian is quite hardy. Can be stored with other energizing stones. Safe in sunlight (may actually benefit from sun energy). Can be stored in soft cloth or with other tumbled stones.',
    'Carnelian is safe to handle and wear. Water safe. Sun safe. Salt safe. Non-toxic. Very safe and stabilizing stone. Suitable for everyone. Energizing but not overwhelming - good for beginners.',
    admin_user_id,
    true
),
(
    'Moonstone',
    'moonstone',
    ARRAY['Selenite (historical)', 'Hecatolite'],
    'White/Cream with blue sheen',
    'Third Eye',
    ARRAY['Cancer', 'Libra', 'Scorpio'],
    'Water',
    'Moon',
    ARRAY['intuition', 'feminine_energy', 'new_beginnings', 'emotional_balance', 'dreams', 'fertility'],
    ARRAY['full_moon', 'running_water', 'smoke'],
    ARRAY['moonlight'],
    'Moonstone is a stone of new beginnings and is strongly connected to the moon and intuition. It enhances psychic abilities and develops clairvoyance. Moonstone calms emotional instability and stress, and stabilizes the emotions, providing calmness.',
    'Use Moonstone in moon rituals, place under pillow for prophetic dreams, wear during full moon, use in fertility magic, carry for emotional balance, meditate with during moon phases.',
    true,
    false,
    true,
    'common',
    'Moonstone has been used in jewelry for millennia, including ancient civilizations of Rome, Greece, and India. Romans believed it was formed from solidified moonlight. In India, moonstone is considered sacred and is believed to bring good fortune. Ancient Rome and Greece associated it with their lunar deities. Art Nouveau jewelers made moonstone very popular in the early 1900s. In India, it was traditional to give moonstone as a wedding gift. Many cultures believed moonstone would bring love and that wearing it would allow you to see your future. Ancient mariners carried it for safe travel.',
    'To use Moonstone: Wear during the full moon to enhance intuition and psychic abilities. Place under pillow to promote prophetic dreams and restful sleep. Hold during meditation to connect with feminine divine energy and inner goddess. Use in moon rituals and esbat celebrations. Place on third eye or crown chakra for spiritual connection. Carry during times of change and new beginnings for emotional support. Wear as jewelry for emotional balance and intuition. Use in fertility and pregnancy rituals. Place in moon water to charge.',
    'Store in moonlight to recharge - especially effective during full moon. Keep in soft cloth to protect from scratches. Can be stored with other moon-associated stones. Avoid prolonged direct sunlight. Room temperature storage is best.',
    'Moonstone is safe to handle and wear. Water safe for short periods. NOT sun safe - can fade in prolonged sunlight. Salt safe but gentle cleansing preferred. Non-toxic. Relatively delicate due to its layered structure - handle with care. Safe energy for everyone including children and pregnancy.',
    admin_user_id,
    true
),
(
    'Obsidian',
    'obsidian',
    ARRAY['Volcanic Glass', 'Nature''s Glass'],
    'Black',
    'Root',
    ARRAY['Sagittarius', 'Scorpio', 'Capricorn'],
    'Earth',
    'Saturn',
    ARRAY['protection', 'grounding', 'truth', 'deep_healing', 'shadow_work', 'psychic_cleansing'],
    ARRAY['full_moon', 'running_water', 'smoke', 'sound', 'earth'],
    ARRAY['moonlight', 'earth'],
    'Obsidian is a highly protective stone that forms a shield against negativity. It is a stone of truth, bringing hidden issues to the surface. Obsidian is powerful for grounding and shadow work. It provides deep soul healing and removes energetic blockages.',
    'Use Obsidian in shadow work and deep healing meditation, carry for protection and grounding, use as a scrying mirror, place on root chakra, use in rituals for cutting cords and releasing the past.',
    true,
    true,
    true,
    'common',
    'Obsidian has been used since prehistoric times, dating back to the Stone Age. The name comes from Obsius, a Roman who discovered a similar stone in Ethiopia according to Pliny the Elder. Ancient cultures around the world used obsidian to make cutting tools, arrowheads, and spear points due to its sharp edges when fractured. Ancient Mesoamerican cultures (Aztec, Mayan) used it for mirrors, tools, and ceremonial knives. It was used in ancient surgery due to its incredibly sharp edge - sharper than modern surgical steel. Black mirrors made from obsidian were used for scrying and divination. Ancient shamans worldwide used it for spiritual work.',
    'To use Obsidian: Use in shadow work and deep emotional healing meditation. Hold or place on body to draw out negative emotions and energy. Use as a scrying mirror (polished obsidian) for divination. Carry for protection and grounding. Place at root chakra for deep grounding work. Use in rituals for cutting energetic cords and releasing the past. Keep in workspace for protection from negative energy. Use in shamanic journeying. Place in home for protection. Use with intention and respect as it is a powerful stone.',
    'Store wrapped or in padded box as it can have very sharp edges if chipped. Can be stored with other grounding, protective stones. Safe in sunlight and moonlight. Store at room temperature.',
    'Obsidian is safe to handle but can have VERY SHARP EDGES if chipped or broken - handle carefully. Water safe. Sun safe. Salt safe. Non-toxic. Can be emotionally intense - work slowly with obsidian. Not recommended for beginners or those who are emotionally fragile. Use grounding stones alongside obsidian. Not suitable for children due to sharp edges and intense energy.',
    admin_user_id,
    true
);

END $$;
