-- =============================================================================
-- GRIMOIRE COLLECTIVE - INTENTIONS DATA
-- =============================================================================
-- Purpose: Complete set of all magical intentions available in the system
-- Dependencies: Requires 03-entity-tables.sql (intentions table definition)
-- Note: Contains both base intentions and entity-specific intentions.
--       Organized by category for easy reference.
-- =============================================================================

INSERT INTO intentions (name, slug, description, category, keywords, usage_guide, related_elements, moon_phases, color) VALUES
    -- Protection & Safety
    ('Protection', 'protection', 'Shielding from negative energy, harm, or unwanted influences', 'protection',
     ARRAY['shield', 'ward', 'defense', 'safety', 'boundaries'],
     'Use for creating protective barriers, warding spaces, deflecting negativity, and maintaining energetic boundaries. Works well with visualization and intention-setting.',
     ARRAY['Fire', 'Earth'],
     ARRAY['Full Moon', 'Waning Moon'],
 '#14B8A6'),
    
    ('Banishing', 'banishing', 'Removing negative energy, habits, or influences from your life', 'protection',
     ARRAY['removal', 'clearing', 'release', 'expel'],
     'Work during waning moon phases to release what no longer serves. Combine with cleansing for maximum effect.',
     ARRAY['Fire', 'Air'],
     ARRAY['Waning Gibbous', 'Last Quarter', 'Waning Crescent'],
 '#EF4444'),
    
    ('Cleansing', 'cleansing', 'Purifying energy, spaces, or objects', 'protection',
     ARRAY['purification', 'clearing', 'sanctification', 'renewal'],
     'Essential before and after magical work. Use smoke, water, sound, or visualization to cleanse spaces and tools.',
     ARRAY['Air', 'Water', 'Fire'],
     ARRAY['New Moon', 'Waning Crescent'],
 '#06B6D4'),
    
    -- Love & Relationships
    ('Love', 'love', 'Attracting or strengthening romantic love', 'relationships',
     ARRAY['romance', 'passion', 'attraction', 'partnership'],
     'Focus on self-love first. For attracting love, work during waxing moon. For strengthening existing relationships, use full moon energy.',
     ARRAY['Water', 'Fire'],
     ARRAY['Waxing Moon', 'Full Moon', 'Friday'],
 '#F43F5E'),
    
    ('Self-Love', 'self-love', 'Cultivating love, acceptance, and compassion for yourself', 'relationships',
     ARRAY['self-care', 'acceptance', 'confidence', 'worth'],
     'The foundation of all other love work. Practice daily affirmations, mirror work, and gentle self-care rituals.',
     ARRAY['Water', 'Spirit'],
     ARRAY['New Moon', 'Full Moon'],
 '#EC4899'),
    
    ('Friendship', 'friendship', 'Attracting or strengthening platonic relationships', 'relationships',
     ARRAY['companionship', 'connection', 'community', 'bonds'],
     'Focus on authentic connection and mutual support. Good for building community and strengthening existing friendships.',
     ARRAY['Air', 'Fire'],
     ARRAY['Waxing Moon', 'Full Moon'],
 '#F59E0B'),
    
    -- Prosperity & Success
    ('Prosperity', 'prosperity', 'Attracting wealth, abundance, and financial success', 'abundance',
     ARRAY['wealth', 'money', 'riches', 'financial'],
     'Combine with practical action. Work during waxing moon to draw prosperity in. Focus on gratitude for current abundance.',
     ARRAY['Earth', 'Fire'],
     ARRAY['Waxing Moon', 'Full Moon', 'Thursday'],
 '#84CC16'),
    
    ('Abundance', 'abundance', 'Attracting plenty in all areas of life', 'abundance',
     ARRAY['plenty', 'overflow', 'blessings', 'wealth'],
     'Broader than just money - includes love, health, opportunities, joy. Cultivate abundance mindset through gratitude.',
     ARRAY['Earth', 'Water'],
     ARRAY['Waxing Moon', 'Full Moon'],
 '#10B981'),
    
    ('Success', 'success', 'Achieving goals and ambitions', 'abundance',
     ARRAY['achievement', 'victory', 'accomplishment', 'goals'],
     'Set clear intentions and back magic with action. Use for job interviews, tests, competitions, or personal goals.',
     ARRAY['Fire', 'Air'],
     ARRAY['Waxing Moon', 'Full Moon', 'Sunday'],
 '#F59E0B'),
    
    ('Employment', 'employment', 'Finding or maintaining work', 'abundance',
     ARRAY['job', 'career', 'work', 'vocation'],
     'Prepare resume and applications first, then enhance with magical work. Focus on right opportunity, not just any job.',
     ARRAY['Earth', 'Air'],
     ARRAY['Waxing Moon', 'New Moon'],
 '#6366F1'),
    
    -- Healing & Health
    ('Healing', 'healing', 'Physical, emotional, or spiritual healing', 'healing',
     ARRAY['recovery', 'wellness', 'health', 'wholeness'],
     'Never replace medical care with magic. Use to support healing process and maintain positive mindset. Consult healthcare providers.',
     ARRAY['Water', 'Earth'],
     ARRAY['Waxing Moon', 'Full Moon'],
 '#22C55E'),
    
    ('Peace', 'peace', 'Bringing calm, tranquility, and inner peace', 'healing',
     ARRAY['calm', 'tranquility', 'serenity', 'stillness'],
     'Essential for mental health and spiritual growth. Practice meditation and create peaceful spaces.',
     ARRAY['Water', 'Air'],
     ARRAY['Waning Moon', 'Full Moon'],
 '#3B82F6'),
    
    ('Balance', 'balance', 'Achieving harmony and equilibrium', 'healing',
     ARRAY['harmony', 'equilibrium', 'stability', 'centeredness'],
     'Work with all elements equally. Focus on balancing aspects of life - work/rest, giving/receiving, physical/spiritual.',
     ARRAY['Spirit', 'Earth'],
     ARRAY['Full Moon', 'Equinoxes'],
 '#8B5CF6'),
    
    ('Sleep', 'sleep', 'Promoting restful sleep and dreams', 'healing',
     ARRAY['rest', 'dreams', 'insomnia', 'relaxation'],
     'Create bedtime rituals, use calming herbs, keep sleep space peaceful. Good for dream work and astral travel.',
     ARRAY['Water', 'Spirit'],
     ARRAY['Waning Moon', 'Dark Moon'],
 '#6366F1'),
    
    -- Spiritual & Psychic
    ('Intuition', 'intuition', 'Enhancing psychic abilities and inner knowing', 'spiritual',
     ARRAY['psychic', 'inner wisdom', 'sixth sense', 'gut feeling'],
     'Trust your first impressions. Practice daily with divination tools. Keep dream journal. Meditate regularly.',
     ARRAY['Water', 'Spirit'],
     ARRAY['Full Moon', 'Dark Moon'],
 '#8B5CF6'),
    
    ('Divination', 'divination', 'Seeking knowledge through magical means', 'spiritual',
     ARRAY['fortune telling', 'prophecy', 'scrying', 'oracle'],
     'Use tarot, runes, pendulum, or other tools. Full moon is most powerful. Clear and charge tools regularly.',
     ARRAY['Air', 'Water', 'Spirit'],
     ARRAY['Full Moon', 'Dark Moon'],
 '#6366F1'),
    
    ('Meditation', 'meditation', 'Deepening meditative practice and spiritual connection', 'spiritual',
     ARRAY['contemplation', 'mindfulness', 'spiritual practice'],
     'Daily practice is key. Create dedicated space. Start with just 5-10 minutes. Use tools that help you focus.',
     ARRAY['Spirit', 'Air'],
     ARRAY['All phases', 'especially Full Moon'],
 '#8B5CF6'),
    
    ('Psychic Abilities', 'psychic-abilities', 'Developing extrasensory perception', 'spiritual',
     ARRAY['ESP', 'clairvoyance', 'telepathy', 'precognition'],
     'Practice exercises daily. Trust your abilities. Protect yourself before psychic work. Ground after sessions.',
     ARRAY['Water', 'Spirit', 'Air'],
     ARRAY['Full Moon', 'Dark Moon'],
 '#8B5CF6'),
    
    ('Spirit Communication', 'spirit-communication', 'Connecting with spirits, ancestors, or guides', 'spiritual',
     ARRAY['mediumship', 'channeling', 'ancestors', 'guides'],
     'Practice proper protection. Set clear boundaries. Honor ancestors. Work respectfully. Ground thoroughly after.',
     ARRAY['Spirit', 'Air'],
     ARRAY['Samhain', 'Dark Moon', 'Waning Moon'],
 '#6B7280'),
    
    ('Astral Projection', 'astral-projection', 'Conscious out-of-body experiences', 'spiritual',
     ARRAY['astral travel', 'OBE', 'soul travel', 'journeying'],
     'Advanced practice. Ensure safety of physical body. Use protective measures. Start with guided meditations.',
     ARRAY['Air', 'Spirit'],
     ARRAY['Dark Moon', 'liminal times'],
 '#06B6D4'),
    
    -- Transformation & Growth
    ('Transformation', 'transformation', 'Major life changes and personal evolution', 'growth',
     ARRAY['change', 'rebirth', 'metamorphosis', 'evolution'],
     'Embrace change as natural. Release old patterns. Work during transitions like Samhain or personal birthdays.',
     ARRAY['Fire', 'Spirit'],
     ARRAY['Dark Moon', 'New Moon', 'Eclipse'],
 '#EC4899'),
    
    ('Growth', 'growth', 'Personal development and expansion', 'growth',
     ARRAY['development', 'learning', 'expansion', 'maturity'],
     'Set intentions for areas you want to develop. Combine magical work with practical learning and practice.',
     ARRAY['Air', 'Earth'],
     ARRAY['Waxing Moon', 'Spring'],
 '#22C55E'),
    
    ('Wisdom', 'wisdom', 'Gaining knowledge and understanding', 'growth',
     ARRAY['knowledge', 'understanding', 'insight', 'enlightenment'],
     'Study, meditate, learn from elders. Combine book learning with experiential wisdom. Keep journals.',
     ARRAY['Air', 'Spirit'],
     ARRAY['Full Moon', 'Waning Moon'],
 '#6366F1'),
    
    ('Courage', 'courage', 'Building bravery and facing fears', 'growth',
     ARRAY['bravery', 'strength', 'valor', 'boldness'],
     'Start small. Face fears gradually. Use before challenging situations. Combine with grounding for balance.',
     ARRAY['Fire', 'Earth'],
     ARRAY['Waxing Moon', 'Tuesday'],
 '#EF4444'),
    
    ('Endurance', 'endurance', 'Sustaining effort and perseverance over time', 'growth',
     ARRAY['perseverance', 'stamina', 'resilience', 'persistence'],
     'Pace yourself. Build gradually. Stay consistent. Rest when needed but keep going.',
     ARRAY['Earth', 'Fire'],
     ARRAY['Waxing Moon', 'Full Moon'],
 '#92400E'),
    
    ('Confidence', 'confidence', 'Building self-assurance and self-esteem', 'growth',
     ARRAY['self-esteem', 'assurance', 'self-belief', 'empowerment'],
     'Practice affirmations. Work on solar plexus chakra. Stand in power poses. Celebrate small victories.',
     ARRAY['Fire', 'Sun'],
     ARRAY['Waxing Moon', 'Sunday'],
 '#F59E0B'),
    
    -- Creativity & Expression
    ('Creativity', 'creativity', 'Enhancing creative abilities and inspiration', 'expression',
     ARRAY['inspiration', 'artistry', 'innovation', 'imagination'],
     'Keep supplies ready. Create sacred creative space. Honor the muse. Regular practice is key.',
     ARRAY['Fire', 'Air'],
     ARRAY['Waxing Moon', 'Full Moon'],
 '#F59E0B'),
    
    ('Communication', 'communication', 'Improving expression and connection', 'expression',
     ARRAY['speech', 'expression', 'clarity', 'articulation'],
     'Work on throat chakra. Practice clear intention. Use before important conversations or presentations.',
     ARRAY['Air', 'Mercury'],
     ARRAY['Waxing Moon', 'Wednesday'],
 '#06B6D4'),
    
    ('Inspiration', 'inspiration', 'Invoking creative and spiritual inspiration', 'expression',
     ARRAY['muse', 'divine inspiration', 'creativity', 'vision'],
     'Create space for inspiration to arrive. Don''t force it. Be open to messages from unexpected sources.',
     ARRAY['Air', 'Fire', 'Spirit'],
     ARRAY['Full Moon', 'dawn'],
 '#F59E0B'),
    
    -- Miscellaneous
    ('Luck', 'luck', 'Attracting good fortune', 'abundance',
     ARRAY['fortune', 'serendipity', 'chance', 'blessing'],
     'Combine with gratitude and positive mindset. Use before gambling, competitions, or risky ventures.',
     ARRAY['Air', 'Jupiter'],
     ARRAY['Waxing Moon', 'Thursday'],
 '#22C55E'),
    
    ('Fertility', 'fertility', 'Encouraging fertility and new beginnings', 'abundance',
     ARRAY['conception', 'pregnancy', 'creation', 'new life'],
     'Can be literal (pregnancy) or symbolic (new projects). Honor the cycle of creation. Work with Earth energy.',
     ARRAY['Earth', 'Water'],
     ARRAY['Waxing Moon', 'Full Moon', 'Spring'],
 '#EC4899'),
    
    ('Beauty', 'beauty', 'Enhancing physical beauty and attractiveness', 'expression',
     ARRAY['glamour', 'attractiveness', 'charm', 'radiance'],
     'Inner beauty reflects outward. Combine with self-care. Focus on confidence and self-acceptance.',
     ARRAY['Water', 'Venus'],
     ARRAY['Waxing Moon', 'Friday'],
 '#EC4899'),
    
    ('Justice', 'justice', 'Seeking fairness and legal success', 'protection',
     ARRAY['legal', 'fairness', 'truth', 'court'],
     'Use for legal matters, court cases, or seeking truth. Combine with truth-speaking and clarity work.',
     ARRAY['Air', 'Fire'],
     ARRAY['Full Moon', 'Sunday'],
 '#6366F1'),
    
    ('Binding', 'binding', 'Restricting harmful actions or people', 'protection',
     ARRAY['restriction', 'limitation', 'prevention', 'stop'],
     'Ethical consideration required. Use only to prevent harm. Consider consequences carefully. Not for manipulation.',
     ARRAY['Earth', 'Saturn'],
     ARRAY['Waning Moon', 'Dark Moon', 'Saturday'],
 '#6B7280'),
    
    ('Grounding', 'grounding', 'Connecting to earth energy and staying present', 'healing',
     ARRAY['centering', 'earthing', 'stability', 'presence'],
     'Essential after magical work. Walk barefoot, use stones, eat root vegetables. Return to physical awareness.',
     ARRAY['Earth'],
     ARRAY['All phases'],
 '#78716C'),
    
    ('Energy', 'energy', 'Increasing vitality and life force', 'healing',
     ARRAY['vitality', 'stamina', 'vigor', 'life force'],
     'Use for physical energy and magical power. Combine with proper rest, nutrition, and exercise.',
     ARRAY['Fire', 'Sun'],
     ARRAY['Waxing Moon', 'Noon', 'Sunday'],
 '#F59E0B'),
    
    ('Focus', 'focus', 'Improving concentration and mental clarity', 'growth',
     ARRAY['concentration', 'attention', 'clarity', 'mindfulness'],
     'Use before study, work, or ritual. Eliminate distractions. Work with Air element for mental clarity.',
     ARRAY['Air', 'Mercury'],
     ARRAY['Waxing Moon', 'Wednesday'],
 '#06B6D4'),
    
    ('Clarity', 'clarity', 'Gaining clear vision and understanding', 'growth',
     ARRAY['clear vision', 'understanding', 'mental clarity', 'truth', 'insight'],
     'Use when seeking truth or understanding. Helps see through illusions and confusion. Excellent for decision-making.',
     ARRAY['Air', 'Spirit'],
     ARRAY['Full Moon', 'New Moon'],
 '#3B82F6'),
    
    ('Dreams', 'dreams', 'Enhancing dream recall and lucid dreaming', 'spiritual',
     ARRAY['lucid dreaming', 'dream recall', 'oneiromancy', 'sleep magic'],
     'Keep dream journal by bed. Set intention before sleep. Use herbs under pillow. Record dreams immediately upon waking.',
     ARRAY['Water', 'Moon'],
     ARRAY['Full Moon', 'Waning Moon'],
 '#8B5CF6'),
    
    ('Travel', 'travel', 'Safe and successful journeys', 'protection',
     ARRAY['journey', 'safe passage', 'adventure', 'protection'],
     'Use before trips for safety and smooth travel. Carry protective items. Set intentions for good experiences.',
     ARRAY['Air', 'Mercury'],
     ARRAY['Waxing Moon', 'Wednesday'],
 '#06B6D4'),
    
    ('Home', 'home', 'Blessing and protecting the home', 'protection',
     ARRAY['household', 'domestic', 'hearth', 'sanctuary'],
     'Create sacred space. Regular cleansing. Set wards. Make home a sanctuary. Use threshold magic.',
     ARRAY['Earth', 'Fire'],
     ARRAY['New Moon', 'Full Moon'],
 '#78716C'),
    
    ('Hex Breaking', 'hex-breaking', 'Removing curses or negative magic', 'protection',
     ARRAY['curse removal', 'jinx breaking', 'uncrossing', 'reversal'],
     'Serious work requiring protection. Cleanse thoroughly before and after. May need repeated workings.',
     ARRAY['Fire', 'Spirit'],
     ARRAY['Waning Moon', 'Dark Moon'],
 '#EF4444'),
    
    -- Sabbat & Life Cycle Themes
    ('Death', 'death', 'Honoring endings, the cycle of life, and mortality', 'spiritual',
     ARRAY['endings', 'mortality', 'transition', 'afterlife', 'letting go'],
     'Honor the natural cycle of life and death. Work during Samhain. Face mortality with reverence. Release what must end.',
     ARRAY['Spirit', 'Earth'],
     ARRAY['Waning Moon', 'Dark Moon', 'Samhain'],
 '#6B7280'),
    
    ('Ancestors', 'ancestors', 'Honoring and connecting with ancestral spirits', 'spiritual',
     ARRAY['lineage', 'family spirits', 'ancestral veneration', 'heritage'],
     'Build ancestor altar. Leave offerings. Learn family history. Honor those who came before. Work especially during Samhain.',
     ARRAY['Spirit', 'Earth'],
     ARRAY['Samhain', 'Dark Moon'],
 '#78716C'),
    
    ('Reflection', 'reflection', 'Looking inward and contemplating life', 'spiritual',
     ARRAY['introspection', 'contemplation', 'self-examination', 'review'],
     'Set aside quiet time. Journal. Review past actions and choices. Prepare for new cycles. Work during waning moon.',
     ARRAY['Water', 'Spirit'],
     ARRAY['Waning Moon', 'Dark Moon'],
 '#6366F1'),
    
    ('New Beginnings', 'new-beginnings', 'Starting fresh and embracing new starts', 'growth',
     ARRAY['fresh start', 'new chapter', 'initiation', 'dawn'],
     'Release the old to make space for the new. Set intentions. Work during new moon or Imbolc. Plant seeds for the future.',
     ARRAY['Air', 'Fire'],
     ARRAY['New Moon', 'Imbolc'],
 '#F59E0B'),
    
    ('Rebirth', 'rebirth', 'Renewal and starting anew after endings', 'growth',
     ARRAY['renewal', 'resurrection', 'revival', 'second chance'],
     'Work after major endings or during Yule/Ostara. Focus on emerging stronger. Phoenix energy.',
     ARRAY['Fire', 'Spirit'],
     ARRAY['Yule', 'Ostara', 'New Moon'],
 '#EF4444'),
    
    ('Purification', 'purification', 'Deep cleansing and making pure', 'protection',
     ARRAY['cleansing', 'sanctification', 'purging', 'baptism'],
     'Stronger than regular cleansing. Work during Imbolc. Use water, fire, or smoke. Prepare for sacred work.',
     ARRAY['Water', 'Fire'],
     ARRAY['Imbolc', 'New Moon'],
 '#06B6D4'),
    
    ('Renewal', 'renewal', 'Refreshing and revitalizing energy', 'healing',
     ARRAY['refresh', 'revitalize', 'restore', 'rejuvenate'],
     'Rest and restore. Take breaks. Reconnect with source. Work during spring or after intense periods.',
     ARRAY['Water', 'Earth'],
     ARRAY['Ostara', 'Waxing Moon'],
 '#22C55E'),
    
    ('Passion', 'passion', 'Igniting intense emotion and desire', 'relationships',
     ARRAY['desire', 'fire', 'intensity', 'enthusiasm'],
     'Work during Beltane or waxing moon. Use fire element. Be clear about intentions. Ethical considerations apply.',
     ARRAY['Fire'],
     ARRAY['Beltane', 'Full Moon'],
 '#EF4444'),
    
    ('Vitality', 'vitality', 'Life force and vibrant energy', 'healing',
     ARRAY['life force', 'vigor', 'zest', 'aliveness'],
     'Cultivate energy and enthusiasm for life. Work during summer or waxing moon. Connect with sun energy.',
     ARRAY['Fire', 'Sun'],
     ARRAY['Litha', 'Waxing Moon'],
 '#F59E0B'),
    
    ('Union', 'union', 'Bringing together and sacred joining', 'relationships',
     ARRAY['joining', 'handfasting', 'partnership', 'merger'],
     'Work for partnerships, handfasting, or bringing elements together. Beltane energy. Balance and harmony.',
     ARRAY['Water', 'Fire'],
     ARRAY['Beltane', 'Full Moon'],
 '#EC4899'),
    
    ('Power', 'power', 'Personal power and magical energy', 'growth',
     ARRAY['strength', 'force', 'potency', 'authority'],
     'Claim your personal power. Work during full moon or Litha. Use solar energy. Stand in your truth.',
     ARRAY['Fire', 'Sun'],
     ARRAY['Full Moon', 'Litha', 'Noon'],
 '#F59E0B'),
    
    ('Strength', 'strength', 'Inner fortitude and resilience', 'growth',
     ARRAY['fortitude', 'resilience', 'endurance', 'perseverance'],
     'Build inner strength. Face challenges. Work with Earth element. Develop staying power.',
     ARRAY['Earth', 'Fire'],
     ARRAY['Waxing Moon'],
 '#78716C'),
    
    ('Harvest', 'harvest', 'Reaping rewards and gathering abundance', 'abundance',
     ARRAY['reaping', 'gathering', 'rewards', 'culmination'],
     'Celebrate achievements. Gather what you''ve sown. Work during Lammas/Mabon. Give thanks for abundance.',
     ARRAY['Earth', 'Fire'],
     ARRAY['Lammas', 'Mabon', 'Full Moon'],
 '#F59E0B'),
    
    ('Gratitude', 'gratitude', 'Giving thanks and appreciation', 'healing',
     ARRAY['thankfulness', 'appreciation', 'blessing', 'recognition'],
     'Essential practice. Daily gratitude journaling. Work during harvest season. Amplifies all other work.',
     ARRAY['Spirit', 'All Elements'],
     ARRAY['Mabon', 'Full Moon'],
 '#22C55E'),
    
    ('Manifestation', 'manifestation', 'Bringing intentions into physical reality', 'abundance',
     ARRAY['creation', 'materialization', 'bringing forth', 'actualization'],
     'Combine visualization with action. Work during waxing/full moon. Be specific. Back magic with practical steps.',
     ARRAY['Earth', 'Fire', 'Spirit'],
     ARRAY['Waxing Moon', 'Full Moon'],
 '#8B5CF6'),
    
    ('Intention Setting', 'intention-setting', 'Clarifying and declaring goals', 'growth',
     ARRAY['goal setting', 'declaration', 'aim', 'purpose'],
     'Set clear, specific intentions. Write them down. Work during new moon. Review regularly.',
     ARRAY['Air', 'Spirit'],
     ARRAY['New Moon'],
 '#3B82F6'),
    
    ('Planning', 'planning', 'Organizing and preparing for the future', 'growth',
     ARRAY['preparation', 'strategy', 'organization', 'foresight'],
     'Think ahead. Make plans. Use Air element for mental clarity. Work during waxing moon or new moon.',
     ARRAY['Air', 'Mercury'],
     ARRAY['New Moon', 'Waxing Moon'],
 '#6366F1'),
    
    ('Rest', 'rest', 'Restoration through stillness and retreat', 'healing',
     ARRAY['stillness', 'retreat', 'restoration', 'pause'],
     'Honor the need for rest. Work during waning/dark moon. Create restorative spaces. Necessary for growth.',
     ARRAY['Water', 'Earth'],
     ARRAY['Waning Moon', 'Dark Moon'],
 '#6B7280'),
    
    -- Entity-Specific Intentions (Candles, Chakras, etc.)
    ('Purity', 'purity', 'Spiritual cleanliness and innocence', 'spiritual',
     ARRAY['cleanliness', 'innocence', 'virginity', 'untainted'],
     'Use white candles and clear quartz. Focus on releasing impurities.',
     ARRAY['Air', 'Spirit'],
     ARRAY['New Moon', 'Full Moon'],
 '#FFFFFF'),
    ('Truth', 'truth', 'Seeking and speaking honesty', 'spiritual',
     ARRAY['honesty', 'authenticity', 'reality', 'veracity'],
     'Work with blue energy and throat chakra. Speak your truth with clarity.',
     ARRAY['Air'],
     ARRAY['Full Moon'],
 '#3B82F6'),
    ('Absorbing Negativity', 'absorbing-negativity', 'Drawing in and neutralizing negative energy', 'protection', 
     ARRAY['absorb', 'neutralize', 'shield', 'negative energy'], 
     'Use with black candles and grounding stones. Visualize negativity being absorbed and transmuted.',
     ARRAY['Earth'],
     ARRAY['Waning Moon', 'Dark Moon'],
 '#000000'),
    ('Emotional Healing', 'emotional-healing', 'Healing emotional wounds and trauma', 'healing',
     ARRAY['emotional', 'wounds', 'trauma', 'heart healing'],
     'Work gently with heart-centered practices. Combine with self-love and compassion work.',
     ARRAY['Water'],
     ARRAY['Waning Moon', 'Full Moon'],
 '#EC4899'),
    ('Romance', 'romance', 'Romantic love and intimate relationships', 'relationships',
     ARRAY['romantic', 'intimate', 'dating', 'partnership'],
     'Focus on attracting or enhancing romantic connections. Use with Venus energy and rose quartz.',
     ARRAY['Water', 'Fire'],
     ARRAY['Waxing Moon', 'Full Moon', 'Friday'],
 '#F43F5E'),
    ('Compassion', 'compassion', 'Cultivating empathy and kindness', 'relationships',
     ARRAY['empathy', 'kindness', 'understanding', 'mercy'],
     'Open your heart to others. Practice loving-kindness meditation.',
     ARRAY['Water'],
     ARRAY['Full Moon'],
 '#EC4899'),
    ('Intimacy', 'intimacy', 'Deep connection and closeness', 'relationships',
     ARRAY['closeness', 'connection', 'vulnerability', 'bonding'],
     'Open your heart. Allow vulnerability. Build trust and connection.',
     ARRAY['Water'],
     ARRAY['Full Moon'],
 '#F43F5E'),
    ('Relationships', 'relationships', 'Connections with others', 'relationships',
     ARRAY['connection', 'partnership', 'bond', 'relating'],
     'Nurture connections. Practice open communication. Value your relationships.',
     ARRAY['Air', 'Water'],
     ARRAY['Waxing Moon', 'Full Moon'],
 '#F59E0B'),
    ('Forgiveness', 'forgiveness', 'Releasing resentment and pardoning', 'healing',
     ARRAY['pardon', 'release', 'letting go', 'mercy'],
     'Release grudges. Practice compassion. Let go of resentment.',
     ARRAY['Water'],
     ARRAY['Waning Moon'],
 '#22C55E'),
    ('Money', 'money', 'Attracting financial abundance and currency', 'abundance',
     ARRAY['cash', 'currency', 'dollars', 'financial flow'],
     'Use green candles and citrine. Focus on specific monetary amounts or steady flow.',
     ARRAY['Earth'],
     ARRAY['Waxing Moon', 'Thursday'],
 '#84CC16'),
    ('Material Matters', 'material-matters', 'Physical world concerns and practical needs', 'abundance',
     ARRAY['practical', 'physical', 'material', 'tangible'],
     'Ground your work in earth energy. Focus on specific, tangible goals.',
     ARRAY['Earth'],
     ARRAY['Waxing Moon'],
 '#78716C'),
    ('Mental Clarity', 'mental-clarity', 'Clear thinking and mental focus', 'growth',
     ARRAY['clarity', 'mental', 'focus', 'clear mind'],
     'Use before important decisions or study. Combine with air element and yellow/blue colors.',
     ARRAY['Air'],
     ARRAY['Waxing Moon'],
 '#06B6D4'),
    ('Joy', 'joy', 'Experiencing happiness and delight', 'emotional',
     ARRAY['happiness', 'delight', 'pleasure', 'celebration'],
     'Celebrate life. Work with sun energy and yellow/orange colors.',
     ARRAY['Fire', 'Sun'],
     ARRAY['Waxing Moon', 'Full Moon'],
 '#F59E0B'),
    ('Enthusiasm', 'enthusiasm', 'Energetic excitement and passion for life', 'emotional',
     ARRAY['excitement', 'passion', 'zest', 'vigor'],
     'Embrace your passions. Channel fire energy for motivation.',
     ARRAY['Fire'],
     ARRAY['Waxing Moon'],
 '#F59E0B'),
    ('Attraction', 'attraction', 'Drawing desired people, opportunities, or circumstances', 'abundance',
     ARRAY['magnetism', 'drawing', 'allure', 'pull'],
     'Focus on what you want to attract. Use visualization and positive energy.',
     ARRAY['Fire', 'Air'],
     ARRAY['Waxing Moon', 'Full Moon'],
 '#EC4899'),
    ('Ambition', 'ambition', 'Drive to achieve goals and succeed', 'growth',
     ARRAY['drive', 'determination', 'aspiration', 'goals'],
     'Set clear goals. Use with Mars energy and red/orange candles.',
     ARRAY['Fire'],
     ARRAY['Waxing Moon', 'Tuesday'],
 '#EF4444'),
    ('Self Esteem', 'self-esteem', 'Valuing and respecting yourself', 'growth',
     ARRAY['self-worth', 'self-respect', 'confidence', 'value'],
     'Recognize your worth. Practice self-respect. Build confidence through action.',
     ARRAY['Fire'],
     ARRAY['Waxing Moon', 'Sunday'],
 '#F59E0B'),
    ('Will', 'will', 'Personal willpower and determination', 'growth',
     ARRAY['willpower', 'determination', 'resolve', 'discipline'],
     'Exercise your will. Make conscious choices. Develop discipline.',
     ARRAY['Fire'],
     ARRAY['Waxing Moon'],
 '#EF4444'),
    ('Expression', 'expression', 'Communicating thoughts and feelings', 'expression',
     ARRAY['communication', 'voice', 'articulation', 'sharing'],
     'Speak your truth. Express yourself freely. Use your voice.',
     ARRAY['Air'],
     ARRAY['Waxing Moon'],
 '#06B6D4'),
    ('Authenticity', 'authenticity', 'Being genuine and true to yourself', 'spiritual',
     ARRAY['genuine', 'real', 'true self', 'integrity'],
     'Honor your truth. Be yourself. Live with integrity.',
     ARRAY['Spirit'],
     ARRAY['All phases'],
 '#8B5CF6'),
    ('Connection to Divine', 'connection-to-divine', 'Connecting with higher power or deity', 'spiritual',
     ARRAY['divine', 'deity', 'higher power', 'sacred connection'],
     'Create sacred space. Use during meditation or prayer. Work with devotional practices.',
     ARRAY['Spirit'],
     ARRAY['Full Moon', 'New Moon'],
 '#8B5CF6'),
    ('Insight', 'insight', 'Deep understanding and perception', 'spiritual',
     ARRAY['understanding', 'realization', 'awareness', 'perception'],
     'Look within. Trust your inner knowing. Seek deeper understanding.',
     ARRAY['Water', 'Spirit'],
     ARRAY['Full Moon', 'Dark Moon'],
 '#6366F1'),
    ('Perception', 'perception', 'Awareness and interpretation', 'spiritual',
     ARRAY['awareness', 'sensing', 'observation', 'discernment'],
     'Expand awareness. Sharpen senses. Practice mindful observation.',
     ARRAY['Air', 'Spirit'],
     ARRAY['Full Moon'],
 '#3B82F6'),
    ('Spirituality', 'spirituality', 'Connection to spiritual practice and growth', 'spiritual',
     ARRAY['spiritual practice', 'devotion', 'faith', 'sacred'],
     'Dedicate regular time to spiritual work. Create sacred space.',
     ARRAY['Spirit'],
     ARRAY['All phases'],
 '#8B5CF6'),
    ('Enlightenment', 'enlightenment', 'Spiritual awakening and illumination', 'spiritual',
     ARRAY['awakening', 'illumination', 'realization', 'nirvana'],
     'Meditate regularly. Seek wisdom. Let go of attachments.',
     ARRAY['Spirit'],
     ARRAY['Full Moon'],
 '#8B5CF6'),
    ('Consciousness', 'consciousness', 'Awareness and presence', 'spiritual',
     ARRAY['awareness', 'presence', 'mindfulness', 'attention'],
     'Be present. Practice mindfulness. Expand your awareness.',
     ARRAY['Spirit'],
     ARRAY['Full Moon', 'All phases'],
 '#8B5CF6'),
    ('Unity', 'unity', 'Oneness and connection with all', 'spiritual',
     ARRAY['oneness', 'wholeness', 'connection', 'universal love'],
     'Recognize interconnection. Meditate on unity. Practice universal love.',
     ARRAY['Spirit'],
     ARRAY['Full Moon'],
 '#8B5CF6'),
    ('Transcendence', 'transcendence', 'Going beyond ordinary limits', 'spiritual',
     ARRAY['beyond', 'higher realm', 'spiritual ascension', 'elevation'],
     'Release limitations. Connect with higher consciousness. Seek spiritual elevation.',
     ARRAY['Spirit', 'Air'],
     ARRAY['Full Moon', 'Eclipse'],
 '#8B5CF6'),
    ('Survival', 'survival', 'Basic needs and instincts for staying alive', 'protection',
     ARRAY['basic needs', 'instinct', 'preservation', 'safety'],
     'Ground yourself. Focus on meeting fundamental needs. Connect with earth element.',
     ARRAY['Earth'],
     ARRAY['Dark Moon', 'Waning Moon'],
 '#78716C'),
    ('Security', 'security', 'Feeling safe and protected', 'protection',
     ARRAY['safety', 'protection', 'shelter', 'stable'],
     'Create protective barriers. Build stable foundations. Work with grounding practices.',
     ARRAY['Earth'],
     ARRAY['Waning Moon'],
 '#78716C'),
    ('Foundation', 'foundation', 'Building solid base and structure', 'grounding',
     ARRAY['base', 'structure', 'support', 'root'],
     'Start with basics. Build slowly and steadily. Create strong foundations.',
     ARRAY['Earth'],
     ARRAY['Waning Moon', 'Dark Moon'],
 '#78716C'),
    ('Stability', 'stability', 'Maintaining balance and steady state', 'grounding',
     ARRAY['balance', 'steady', 'equilibrium', 'anchored'],
     'Stay centered and grounded. Maintain routines. Build consistent practices.',
     ARRAY['Earth'],
     ARRAY['Waning Moon', 'Full Moon'],
 '#78716C'),
    ('Sexuality', 'sexuality', 'Sexual energy and expression', 'relationships',
     ARRAY['sexual', 'sensual', 'desire', 'libido'],
     'Honor your body. Embrace sensuality. Work with sacral chakra and water element.',
     ARRAY['Water', 'Fire'],
     ARRAY['Waxing Moon', 'Full Moon'],
 '#F43F5E'),
    ('Pleasure', 'pleasure', 'Experiencing joy and sensual delight', 'emotional',
     ARRAY['enjoyment', 'delight', 'sensual', 'satisfaction'],
     'Allow yourself to feel good. Embrace what brings you joy.',
     ARRAY['Water'],
     ARRAY['Waxing Moon', 'Full Moon'],
 '#EC4899'),
    ('Emotions', 'emotions', 'Feeling and expressing emotional states', 'emotional',
     ARRAY['feelings', 'emotional', 'sentiment', 'mood'],
     'Honor your feelings. Allow emotions to flow. Practice emotional awareness.',
     ARRAY['Water'],
     ARRAY['All phases'],
 '#06B6D4'),
    ('Animals', 'animals', 'Working with and honoring animals', 'nature',
     ARRAY['pets', 'animal spirits', 'familiars', 'wildlife'],
     'Honor animal companions. Work with animal spirit guides.',
     ARRAY['Earth', 'Spirit'],
     ARRAY['Full Moon'],
 '#78716C')
ON CONFLICT (slug) DO NOTHING;

