-- =============================================================================
-- RUNE DATA (Elder Futhark - 24 Runes)
-- =============================================================================

-- Freya's Aett (First Eight)
INSERT INTO runes (name, slug, pronunciation, letter_equivalent, position_in_futhark, aett, keywords, upright_meaning, reversed_meaning, merkstave_meaning, description, literal_meaning, esoteric_meaning, divinatory_meaning, advice, challenge, gift, in_love, in_work, in_health, spiritual_lesson, galdr, stances) VALUES
('Fehu', 'fehu', 'FAY-who', 'F', 1, 'freyja', 
 ARRAY['wealth', 'abundance', 'prosperity', 'cattle', 'mobile property'],
 'Abundance, prosperity, and fulfillment. Mobile wealth and new beginnings.',
 'Loss, greed, or financial setbacks. Blocked abundance.',
 'Poverty, loss, or squandered opportunities.',
 'First rune of the Elder Futhark, representing moveable wealth and the primal creative force.',
 'Cattle, wealth',
 'The power of creative abundance and the circulation of energy',
 'Financial gain, new opportunities, and the manifestation of desires',
 'Share your abundance and wealth will flow to you',
 'To learn proper stewardship of resources',
 'Prosperity consciousness and generative power',
 'Passion and fertility in relationships',
 'Financial success and career advancement',
 'Vital energy and good health',
 'True wealth comes from what you give, not what you hoard',
 'fe fe fe fu fa fi', 
 'Arms extended upward at 45-degree angles'),

('Uruz', 'uruz', 'OO-rooz', 'U', 2, 'freyja',
 ARRAY['strength', 'vitality', 'primal power', 'aurochs', 'wild ox'],
 'Strength, vitality, and primal power. Physical health and stamina.',
 'Weakness, ill health, or misdirected force.',
 'Lack of strength, missed opportunities',
 'The aurochs (wild ox) represents untamed strength, primal vitality, and the life force.',
 'Aurochs, wild ox',
 'Raw primal energy and the power of manifestation in the physical world',
 'Physical strength, health, and the power to overcome obstacles',
 'Use your strength wisely and honor your physical body',
 'To channel raw power constructively',
 'Vitality, endurance, and primal life force',
 'Passionate physical connection',
 'Stamina to complete difficult tasks',
 'Physical vitality and healing',
 'True strength is gentle and knows when to rest',
 'ur ur ur ur ur', 
 'Wide stance, arms curved downward'),

('Thurisaz', 'thurisaz', 'THOO-ree-sahz', 'TH', 3, 'freyja',
 ARRAY['protection', 'defense', 'thorn', 'giant', 'boundary'],
 'Protection, boundaries, and defensive force. Gateway and threshold.',
 'Danger, defenselessness, or betrayal.',
 'Vulnerability, conflict, or poor boundaries',
 'The thorn or giant represents protective force, boundaries, and the power to defend.',
 'Thorn, giant',
 'Protective force and the power of conscious defense',
 'Protection through awareness, setting healthy boundaries',
 'Establish clear boundaries and protect what matters',
 'To know when to defend and when to yield',
 'Protective awareness and the power of the threshold',
 'Protecting the relationship from outside forces',
 'Defending your work and asserting boundaries',
 'Immune system strength',
 'The best defense is conscious awareness',
 'thurisaz thurisaz thurisaz', 
 'One arm extended forward, defensive stance'),

('Ansuz', 'ansuz', 'AHN-sooz', 'A', 4, 'freyja',
 ARRAY['communication', 'divine inspiration', 'wisdom', 'Odin', 'ancestral power'],
 'Divine inspiration, communication, and ancestral wisdom. The voice of Odin.',
 'Miscommunication, lack of clarity, or blocked inspiration.',
 'Deception, manipulation of words',
 'The mouth of Odin, representing divine communication, wisdom, and inspired speech.',
 'God, mouth, communication',
 'Divine inspiration flowing through human consciousness',
 'Listen for divine guidance and speak your truth clearly',
 'Seek wisdom before speaking and listen deeply',
 'To become a clear channel for truth',
 'Inspired speech and ancestral wisdom',
 'Deep meaningful communication',
 'Clear communication and inspired ideas',
 'Mental clarity and cognitive health',
 'Words have power - use them wisely',
 'ansuz ansuz ansuz', 
 'Arms raised in receiving position'),

('Raidho', 'raidho', 'RYE-though', 'R', 5, 'freyja',
 ARRAY['journey', 'travel', 'rhythm', 'wheel', 'right action'],
 'Journey, travel, and movement. Rhythm and right action.',
 'Disrupted journey, crisis, or rigidity.',
 'Stagnation, wrong path, or upheaval',
 'The wagon wheel represents journey, rhythm, and the path of right action.',
 'Wagon, journey',
 'The rhythm of life and the journey of the soul',
 'A journey is beginning - physical, spiritual, or metaphorical',
 'Trust the journey and maintain your rhythm',
 'To stay on the path despite obstacles',
 'The power of aligned movement',
 'The journey you take together',
 'Career progression and business travel',
 'Movement and circulation for health',
 'The journey is as important as the destination',
 'raidho raidho raidho', 
 'Walking meditation, rhythmic movement'),

('Kenaz', 'kenaz', 'KEN-ahz', 'K', 6, 'freyja',
 ARRAY['torch', 'knowledge', 'creativity', 'opening', 'illumination'],
 'Knowledge, illumination, and creative fire. Opening and revelation.',
 'Darkness, ignorance, or loss of way.',
 'Closed off, blocked creativity',
 'The torch represents illumination, knowledge, and the light that dispels darkness.',
 'Torch, fire',
 'The flame of inspiration and creative intelligence',
 'Illumination is coming - knowledge that dispels confusion',
 'Seek knowledge and let your light shine',
 'To transform darkness into light',
 'Creative fire and illuminating wisdom',
 'Passion and creative intimacy',
 'Inspired creativity and innovation',
 'Healing warmth and vitality',
 'Be a light for others without burning yourself out',
 'kenaz kenaz kenaz', 'Arms crossed at chest then opening outward'),

('Gebo', 'gebo', 'GEH-bow', 'G', 7, 'freyja',
 ARRAY['gift', 'partnership', 'exchange', 'balance', 'union'],
 'Gift, partnership, and balanced exchange. Union and generosity.',
 NULL,
 NULL,
 'The gift represents balanced exchange, partnership, and the sacred bond between beings.',
 'Gift, exchange',
 'Sacred exchange and the balance of giving and receiving',
 'A gift is coming or a partnership forming - honor the exchange',
 'Give freely and receive graciously',
 'To maintain balance in all exchanges',
 'The power of true partnership',
 'Balanced give and take in love',
 'Partnerships and fair contracts',
 'Balance between exertion and rest',
 'True gifts expect nothing in return',
 'gebo gebo gebo', 
 'Arms crossed forming an X'),

('Wunjo', 'wunjo', 'WOON-yo', 'W', 8, 'freyja',
 ARRAY['joy', 'harmony', 'fellowship', 'pleasure', 'clan'],
 'Joy, harmony, and fellowship. Pleasure and well-being.',
 'Sorrow, alienation, or discord.',
 'Depression, isolation, or conflict',
 'The joy rune represents harmony, fellowship, and the happiness found in community.',
 'Joy, pleasure',
 'The bliss of harmony and shared joy',
 'Joy is available now - embrace harmony and connection',
 'Cultivate joy and share it with others',
 'To find joy despite difficulties',
 'True happiness and harmonious relationships',
 'Joy and harmony in partnership',
 'Positive work environment and team spirit',
 'Emotional well-being and happiness',
 'Joy shared is joy multiplied',
 'wunjo wunjo wunjo', 
 'Open arms, welcoming stance');

-- Heimdall's Aett (Second Eight)
INSERT INTO runes (name, slug, pronunciation, letter_equivalent, position_in_futhark, aett, keywords, upright_meaning, reversed_meaning, merkstave_meaning, description, literal_meaning, esoteric_meaning, divinatory_meaning, advice, challenge, gift, in_love, in_work, in_health, spiritual_lesson, galdr, stances) VALUES
('Hagalaz', 'hagalaz', 'HAH-gah-lahz', 'H', 9, 'heimdall',
 ARRAY['hail', 'disruption', 'crisis', 'transformation', 'uncontrolled forces'],
 'Disruption, crisis, and uncontrolled forces. Transformation through challenge.',
 NULL,
 NULL,
 'Hail represents sudden disruption, natural forces beyond control, and transformation through crisis.',
 'Hail, hailstorm',
 'Destructive force that clears the way for new growth',
 'Disruption is necessary - surrender to forces beyond your control',
 'Accept what cannot be changed and find strength in adversity',
 'To remain centered during chaos',
 'Resilience and the ability to weather storms',
 'Sudden upheaval that tests the relationship',
 'Unexpected challenges or setbacks',
 'Health crisis that demands attention',
 'What breaks you open also breaks you through',
 'hagalaz hagalaz hagalaz', 
 'Arms forming sleet pattern'),

('Nauthiz', 'nauthiz', 'NOW-theez', 'N', 10, 'heimdall',
 ARRAY['need', 'constraint', 'necessity', 'resistance', 'friction'],
 'Need, constraint, and necessity. Friction creates fire.',
 'Impatience, poverty, or desperation.',
 'Neediness, restriction, or lack',
 'Need represents constraint, necessity, and the friction that creates transformation.',
 'Need, necessity',
 'The productive friction of constraint that sparks creativity',
 'Necessity is the mother of invention - embrace constraints',
 'Work with limitations rather than against them',
 'To find freedom within constraint',
 'Creative resourcefulness and determination',
 'Working through difficulties together',
 'Doing what must be done despite obstacles',
 'Acceptance of physical limitations',
 'Need teaches us what is truly necessary',
 'nauthiz nauthiz nauthiz', 
 'Crossed arms, bound position'),

('Isa', 'isa', 'EE-sah', 'I', 11, 'heimdall',
 ARRAY['ice', 'stillness', 'standstill', 'patience', 'preservation'],
 'Ice, stillness, and standstill. Patience and preservation.',
 NULL,
 NULL,
 'Ice represents stillness, preservation, and the waiting period before spring.',
 'Ice, standstill',
 'The power of stillness and the wisdom of waiting',
 'A time of waiting - be still and preserve your energy',
 'Practice patience and wait for the right moment',
 'To embrace stillness without stagnation',
 'Clarity through stillness',
 'Cooling off period or frozen emotions',
 'Pause in career progress',
 'Rest and recuperation needed',
 'In stillness, clarity emerges',
 'isa isa isa', 
 'Straight vertical stance, complete stillness'),

('Jera', 'jera', 'YEH-rah', 'J', 12, 'heimdall',
 ARRAY['year', 'harvest', 'cycles', 'patience', 'reward'],
 'Year, harvest, and natural cycles. Reward for effort.',
 NULL,
 NULL,
 'The year represents natural cycles, harvest, and the rewards that come in their proper season.',
 'Year, harvest',
 'The turning of the wheel and natural timing',
 'Your efforts will be rewarded - trust in natural timing',
 'Be patient and trust the natural cycles',
 'To honor natural timing',
 'Patience and the rewards of right action',
 'Relationship maturing over time',
 'Career efforts bearing fruit',
 'Natural healing cycles',
 'Everything has its season',
 'jera jera jera', 
 'Circular motion, turning with the seasons'),

('Eihwaz', 'eihwaz', 'AY-wahz', 'EI', 13, 'heimdall',
 ARRAY['yew tree', 'endurance', 'death and rebirth', 'transformation', 'reliability'],
 'Endurance, transformation, and the mysteries of death and rebirth.',
 'Confusion, weakness, or fear of change.',
 'Blocked transformation, fear',
 'The yew tree represents endurance, death and rebirth, and the mysteries of transformation.',
 'Yew tree, bow',
 'The axis between worlds and the power of transformation',
 'Transformation through trial - you have the strength to endure',
 'Trust in your resilience and embrace transformation',
 'To transform through difficulty',
 'Endurance and the power to transform',
 'Relationship transformed through challenges',
 'Perseverance through difficult times',
 'Healing through crisis',
 'What doesn''t kill you makes you stronger',
 'eihwaz eihwaz eihwaz', 
 'Balanced stance, spine straight'),

('Perthro', 'perthro', 'PER-throw', 'P', 14, 'heimdall',
 ARRAY['dice cup', 'fate', 'mystery', 'chance', 'hidden things'],
 'Mystery, fate, and chance. Hidden things revealed.',
 'Secrets, disappointment, or bad luck.',
 'Revealed secrets, addiction',
 'The dice cup represents fate, mystery, and the unknown forces that shape our lives.',
 'Dice cup, lot cup',
 'The mysteries of fate and the web of wyrd',
 'Mysteries are at play - not everything can be known',
 'Accept mystery and trust in fate',
 'To surrender to the unknown',
 'Intuition and hidden knowledge',
 'Mysterious attraction or fated meeting',
 'Unexpected opportunities',
 'Hidden health issues surfacing',
 'Some things are meant to remain mysterious',
 'perthro perthro perthro', 
 'Cupped hands, receptive position'),

('Algiz', 'algiz', 'ALL-geez', 'Z', 15, 'heimdall',
 ARRAY['elk', 'protection', 'defense', 'higher self', 'sanctuary'],
 'Protection, defense, and connection to higher self. Divine shield.',
 'Vulnerability, danger, or lack of protection.',
 'Hidden danger, paranoia',
 'The elk represents divine protection, connection to higher self, and spiritual defense.',
 'Elk, protection',
 'Divine protection and connection to higher consciousness',
 'You are protected - reach upward for divine guidance',
 'Stay connected to your higher self and trust in protection',
 'To be a channel for protective force',
 'Divine protection and spiritual connection',
 'Spiritual connection in relationship',
 'Protection from workplace negativity',
 'Strong immune system and spiritual health',
 'The universe protects those who align with highest good',
 'algiz algiz algiz', 
 'Arms raised in Y position'),

('Sowilo', 'sowilo', 'SO-wee-lo', 'S', 16, 'heimdall',
 ARRAY['sun', 'success', 'wholeness', 'victory', 'life force'],
 'Sun, success, and wholeness. Victory and life force.',
 NULL,
 NULL,
 'The sun represents success, wholeness, victory, and the life-giving force of the sun.',
 'Sun, life force',
 'The wholeness and victory of the integrated self',
 'Success is assured - victory and wholeness are yours',
 'Shine your light and claim your victory',
 'To integrate all parts of yourself',
 'Wholeness and radiant success',
 'Warmth and joy in love',
 'Success and recognition',
 'Vitality and radiant health',
 'You are the light you''ve been seeking',
 'sowilo sowilo sowilo', 
 'Arms forming lightning bolt, triumphant stance');

-- Tyr's Aett (Third Eight)
INSERT INTO runes (name, slug, pronunciation, letter_equivalent, position_in_futhark, aett, keywords, upright_meaning, reversed_meaning, merkstave_meaning, description, literal_meaning, esoteric_meaning, divinatory_meaning, advice, challenge, gift, in_love, in_work, in_health, spiritual_lesson, galdr, stances) VALUES
('Tiwaz', 'tiwaz', 'TEE-wahz', 'T', 17, 'tyr',
 ARRAY['warrior', 'justice', 'honor', 'sacrifice', 'sky god'],
 'Justice, honor, and self-sacrifice. The warrior spirit.',
 'Injustice, lack of motivation, or conflict.',
 'Defeat, over-sacrifice',
 'Tyr the sky god represents justice, honor, self-sacrifice, and the warrior spirit.',
 'Tyr (god), arrow',
 'The warrior''s path and the price of justice',
 'Stand in your truth and honor your commitments',
 'Act with honor and be willing to make necessary sacrifices',
 'To know what is worth fighting for',
 'Courage and integrity',
 'Honor and loyalty in relationship',
 'Leadership and standing up for what''s right',
 'Recovery through discipline',
 'True victory is won through honor',
 'tiwaz tiwaz tiwaz', 
 'Warrior stance, arrow pointed up'),

('Berkano', 'berkano', 'BER-kah-no', 'B', 18, 'tyr',
 ARRAY['birch', 'birth', 'growth', 'mother', 'nurturing'],
 'Birth, growth, and nurturing. The divine feminine.',
 'Family troubles, anxiety, or abandonment.',
 'Blocked growth, family issues',
 'The birch tree represents birth, growth, nurturing, and the divine feminine.',
 'Birch, birch goddess',
 'The nurturing force of the divine mother',
 'New beginnings and gentle growth - nurture what is arising',
 'Tend to new growth with patience and care',
 'To nurture without smothering',
 'Nurturing creativity and growth',
 'Fertility and new beginnings in love',
 'New projects coming to life',
 'Healing and recovery',
 'Growth happens in its own time',
 'berkano berkano berkano', 
 'Curved protective stance, embracing'),

('Ehwaz', 'ehwaz', 'EH-wahz', 'E', 19, 'tyr',
 ARRAY['horse', 'movement', 'partnership', 'trust', 'progress'],
 'Horse, movement, and partnership. Trust and progress.',
 'Restlessness, lack of progress, or betrayal.',
 'Reckless haste, distrust',
 'The horse represents movement, partnership, trust, and harmonious progress.',
 'Horse, steed',
 'The sacred bond between rider and horse',
 'Progress through partnership - trust and move forward together',
 'Build trust and move in harmony with others',
 'To balance independence with interdependence',
 'Trust and harmonious movement',
 'Partnership built on trust and mutual respect',
 'Teamwork and cooperation',
 'Physical movement for health',
 'Together we go further',
 'ehwaz ehwaz ehwaz', 
 'Parallel movement, mirrored stance'),

('Mannaz', 'mannaz', 'MAH-nahz', 'M', 20, 'tyr',
 ARRAY['human', 'self', 'humanity', 'divine structure', 'social order'],
 'The self, humanity, and human nature. Divine structure.',
 'Depression, isolation, or self-delusion.',
 'Selfishness, manipulation',
 'The human represents the self, humanity, divine structure, and our place in society.',
 'Human, mankind',
 'The divine structure of human consciousness',
 'Know thyself - examine your place in the human family',
 'Study yourself and your relationships with others',
 'To be fully human and fully divine',
 'Self-awareness and human connection',
 'Understanding each other as humans',
 'Networking and human resources',
 'Mental and emotional health',
 'To be human is to be divine',
 'mannaz mannaz mannaz', 
 'Standing tall, arms at sides'),

('Laguz', 'laguz', 'LAH-gooz', 'L', 21, 'tyr',
 ARRAY['water', 'flow', 'emotions', 'intuition', 'deep self'],
 'Water, flow, and emotions. Intuition and the deep self.',
 'Confusion, poor judgment, or being overwhelmed.',
 'Drowning emotions, confusion',
 'Water represents flow, emotions, intuition, and the mysteries of the deep self.',
 'Water, lake',
 'The flow of the unconscious and emotional wisdom',
 'Flow with your emotions and trust your intuition',
 'Let go and allow yourself to flow',
 'To navigate emotional depths',
 'Emotional intelligence and intuitive knowing',
 'Deep emotional connection',
 'Going with the flow at work',
 'Emotional and fluid health',
 'Resistance creates turbulence - flow creates peace',
 'laguz laguz laguz', 
 'Fluid, wave-like movements'),

('Ingwaz', 'ingwaz', 'ING-wahz', 'NG', 22, 'tyr',
 ARRAY['seed', 'potential', 'gestation', 'fertility', 'Ing (god)'],
 'Seed, potential, and gestation. Fertility and completion.',
 NULL,
 NULL,
 'Ing the fertility god represents the seed, potential, gestation, and the completion of cycles.',
 'Ing (god), seed',
 'The potential within and the completion of cycles',
 'Something is gestating - give it time to develop',
 'Trust in the gestation period',
 'To nurture potential into manifestation',
 'Creative potential and completion',
 'Relationship reaching maturity',
 'Projects reaching completion',
 'Reproductive health and vitality',
 'All things grow from seeds in darkness',
 'ingwaz ingwaz ingwaz', 
 'Contained, centered stance'),

('Dagaz', 'dagaz', 'DAH-gahz', 'D', 23, 'tyr',
 ARRAY['day', 'dawn', 'breakthrough', 'awakening', 'transformation'],
 'Day, dawn, and breakthrough. Awakening and transformation.',
 NULL,
 NULL,
 'The day represents dawn, breakthrough, awakening, and transformative light.',
 'Day, dawn',
 'The breakthrough of awakening consciousness',
 'A breakthrough is coming - darkness gives way to light',
 'Embrace the transformation that is unfolding',
 'To step into the light of awareness',
 'Clarity and transformative awakening',
 'Sudden clarity in relationship',
 'Career breakthrough',
 'Sudden healing or recovery',
 'After the darkest hour comes the dawn',
 'dagaz dagaz dagaz', 
 'Arms forming infinity symbol, balanced'),

('Othala', 'othala', 'OH-thah-lah', 'O', 24, 'tyr',
 ARRAY['homeland', 'inheritance', 'ancestry', 'property', 'tradition'],
 'Homeland, inheritance, and ancestral property. Tradition and roots.',
 'Lack of roots, intolerance, or loss of inheritance.',
 'Prejudice, homelessness',
 'The homeland represents inheritance, ancestral property, tradition, and one''s roots.',
 'Homeland, inheritance',
 'The ancestral legacy and spiritual inheritance',
 'Honor your roots and ancestral wisdom',
 'Connect with your heritage and honor your ancestors',
 'To integrate ancestral wisdom',
 'Tradition and spiritual inheritance',
 'Family legacy in relationship',
 'Business inheritance or property',
 'Genetic health patterns',
 'Your ancestors live through you',
 'othala othala othala', 
 'Rooted stance, arms forming ancestral link');

-- Notification
DO $$ 
BEGIN 
    RAISE NOTICE '✓ 24 Elder Futhark runes inserted';
END $$;
