-- =============================================================================
-- TAROT CARD DATA
-- =============================================================================
-- Major Arcana (22 cards) + Sample Minor Arcana
-- Full 78-card deck can be expanded later

-- =============================================================================
-- MAJOR ARCANA (0-21)
-- =============================================================================

INSERT INTO tarot_cards (name, slug, card_type, suit, number, arcana_number, keywords, upright_meaning, reversed_meaning, description, symbolism, numerological_meaning, archetype, life_lesson, spiritual_message, shadow_work, advice, questions_to_ask, affirmation, love_career_health, timing, yes_no) VALUES
('The Fool', 'the-fool', 'major', NULL, 0, 0,
 ARRAY['new beginnings', 'innocence', 'spontaneity', 'free spirit'],
 'New beginnings, innocence, spontaneity, and a free spirit. Taking a leap of faith.',
 'Recklessness, taken advantage of, inconsideration.',
 'The Fool represents new beginnings, having faith in the future, being inexperienced, not knowing what to expect, having beginner''s luck, improvisation and believing in the universe.',
 'The Fool stands at the edge of a cliff, representing the leap of faith into the unknown. The white rose symbolizes purity, the small dog represents loyalty, and the mountains in the background represent the challenges ahead.',
 'Zero represents unlimited potential, the void from which all creation emerges.',
 'The Innocent, The Seeker',
 'Trust in the journey and embrace the unknown with an open heart.',
 'You are entering a new phase - step forward with faith.',
 'Where am I being naive? What am I avoiding through innocence?',
 'Take that leap of faith, but look before you leap.',
 ARRAY['Am I ready for a new adventure?', 'What would I do if I had no fear?', 'Where do I need more spontaneity?'],
 'I trust in the journey and embrace new beginnings.',
 '{"love": "New relationship or fresh start", "career": "New job or career path", "health": "Time to try new health approaches"}',
 'Beginning of spring, new moon',
 'yes'),

('The Magician', 'the-magician', 'major', NULL, 1, 1,
 ARRAY['manifestation', 'resourcefulness', 'power', 'inspired action'],
 'Manifestation, resourcefulness, power, and inspired action. You have the tools you need.',
 'Manipulation, poor planning, untapped potential.',
 'The Magician is about conscious awareness, taking action and using your skills and talents to manifest your goals.',
 'The Magician stands with one arm pointing to the sky and one to the earth, channeling divine power. The infinity symbol above his head represents unlimited potential, and the four suit symbols (wand, cup, sword, pentacle) show mastery over all elements.',
 'One represents unity, focus, and the power to create.',
 'The Creator, The Manifestor',
 'You have all the tools you need - use them consciously.',
 'As above, so below - you are a channel for manifestation.',
 'Where am I deceiving myself or others? What power am I not using?',
 'Focus your will and manifest your desires.',
 ARRAY['What am I ready to manifest?', 'How can I use my skills more effectively?', 'Where am I not taking action?'],
 'I have the power to create my reality.',
 '{"love": "Magnetic attraction, taking initiative", "career": "Skills and talents lead to success", "health": "Mind-body connection, holistic healing"}',
 'Immediate action, mercury retrograde',
 'yes'),

('The High Priestess', 'the-high-priestess', 'major', NULL, 2, 2,
 ARRAY['intuition', 'sacred knowledge', 'divine feminine', 'the subconscious mind'],
 'Intuition, sacred knowledge, divine feminine, and the subconscious mind. Trust your inner voice.',
 'Secrets, disconnected from intuition, withdrawal.',
 'The High Priestess signifies spiritual enlightenment, inner illumination, divine knowledge and wisdom.',
 'She sits between two pillars marked B and J (Boaz and Jachin), representing duality. The crescent moon at her feet shows connection to the divine feminine, and the Torah in her lap represents hidden knowledge.',
 'Two represents duality, balance, and the gateway between worlds.',
 'The Mystic, The Intuitive',
 'Listen to your intuition and honor your inner knowing.',
 'The answers you seek lie within - go inward.',
 'What truths am I hiding from myself? Where am I ignoring my intuition?',
 'Trust your intuition and look beyond the surface.',
 ARRAY['What is my intuition telling me?', 'What secrets need to be revealed?', 'How can I connect more deeply with my inner wisdom?'],
 'I trust my intuition and inner wisdom.',
 '{"love": "Mystery and depth, spiritual connection", "career": "Trust your gut, research hidden information", "health": "Listen to your body, hormonal balance"}',
 'Full moon, nighttime',
 'unclear'),

('The Empress', 'the-empress', 'major', NULL, 3, 3,
 ARRAY['femininity', 'beauty', 'nature', 'nurturing', 'abundance'],
 'Femininity, beauty, nature, nurturing, and abundance. Creative expression.',
 'Creative block, dependence on others, smothering.',
 'The Empress represents abundance, nurturing, fertility, and the embodiment of Mother Nature.',
 'She sits on a throne surrounded by nature, holding a scepter. The Venus symbol on her heart-shaped shield represents love, and the wheat field symbolizes abundance.',
 'Three represents creativity, growth, and manifestation.',
 'The Mother, The Nurturer',
 'Abundance flows when you nurture yourself and others.',
 'You are a channel for creative life force.',
 'Where am I smothering instead of nurturing? How do I need to mother myself?',
 'Nurture your creativity and abundance will flow.',
 ARRAY['What needs nurturing in my life?', 'How can I express my creativity?', 'Where do I need more self-care?'],
 'I am abundant and creative.',
 '{"love": "Fertility, pregnancy, nurturing partnership", "career": "Creative projects flourishing", "health": "Fertility, pregnancy, or need for self-care"}',
 'Nine months, harvest time',
 'yes'),

('The Emperor', 'the-emperor', 'major', NULL, 4, 4,
 ARRAY['authority', 'establishment', 'structure', 'father figure'],
 'Authority, establishment, structure, and father figure. Leadership and stability.',
 'Domination, excessive control, lack of discipline.',
 'The Emperor represents authority, structure, stability, and the masculine principle of leadership.',
 'He sits on a stone throne decorated with ram heads (Aries), holding a scepter and ankh. The barren mountains behind him represent his unyielding power.',
 'Four represents structure, stability, and manifestation in the material world.',
 'The Father, The Leader',
 'Create structure and take responsibility for your realm.',
 'True power comes from disciplined action.',
 'Where am I being too controlling? What structure do I need to create?',
 'Establish boundaries and create lasting structures.',
 ARRAY['Where do I need more discipline?', 'What structures need to be created?', 'How can I embody healthy authority?'],
 'I create structure and stability in my life.',
 '{"love": "Commitment, stability, father figure", "career": "Leadership, promotion, starting business", "health": "Physical strength, structured health routine"}',
 'Long-term planning, Aries season',
 'yes'),

('The Hierophant', 'the-hierophant', 'major', NULL, 5, 5,
 ARRAY['spiritual wisdom', 'religious beliefs', 'conformity', 'tradition', 'institutions'],
 'Spiritual wisdom, religious beliefs, conformity, tradition, and institutions. Seeking guidance.',
 'Personal beliefs, freedom, challenging tradition.',
 'The Hierophant represents tradition, conformity, moral compass, and spiritual guidance from institutions.',
 'He sits between two pillars in a sacred space, holding the papal cross. Two acolytes kneel before him, representing the passing down of sacred knowledge.',
 'Five represents tradition, spiritual law, and the teaching of sacred knowledge.',
 'The Teacher, The Priest',
 'Honor tradition but find your own spiritual path.',
 'Seek guidance from those who have walked the path before.',
 'Where am I blindly following? What beliefs need questioning?',
 'Seek wisdom from tradition and teachers.',
 ARRAY['What traditions serve me?', 'Who are my spiritual teachers?', 'Where do I need guidance?'],
 'I honor tradition while finding my own path.',
 '{"love": "Traditional relationship, marriage, shared values", "career": "Mentor, education, corporate structure", "health": "Conventional medicine, seeking professional help"}',
 'Taurus season, traditional timing',
 'yes'),

('The Lovers', 'the-lovers', 'major', NULL, 6, 6,
 ARRAY['love', 'harmony', 'relationships', 'values alignment', 'choices'],
 'Love, harmony, relationships, values alignment, and choices. Union and partnership.',
 'Self-love, disharmony, imbalance, misalignment of values.',
 'The Lovers represents love, harmony, relationships, and the choices we make based on our values.',
 'Adam and Eve stand beneath the angel Raphael, representing the union of masculine and feminine. The tree of knowledge and the tree of life represent choices and consequences.',
 'Six represents harmony, balance, and the union of opposites.',
 'The Lover, The Partner',
 'Choose based on love and alignment with your values.',
 'The most important relationship is with yourself.',
 'Where am I out of alignment? What choice am I avoiding?',
 'Make choices aligned with your heart and values.',
 ARRAY['What choice am I facing?', 'Are my relationships aligned with my values?', 'How can I love myself more?'],
 'I choose love and alignment.',
 '{"love": "Soulmate, deep connection, choice in relationship", "career": "Partnership, collaboration, value-based work", "health": "Balance, heart health, sexual health"}',
 'Gemini season, spring',
 'yes'),

('The Chariot', 'the-chariot', 'major', NULL, 7, 7,
 ARRAY['control', 'willpower', 'success', 'action', 'determination'],
 'Control, willpower, success, action, and determination. Victory through discipline.',
 'Opposition, lack of direction, self-discipline.',
 'The Chariot represents victory, determination, willpower, and overcoming obstacles through focus.',
 'A victorious warrior rides a chariot pulled by two sphinxes - one black, one white - representing duality controlled through willpower.',
 'Seven represents victory, spiritual mastery, and the triumph of will.',
 'The Warrior, The Victor',
 'Victory comes through focused will and determination.',
 'You have the power to overcome any obstacle.',
 'Where am I being pulled in different directions? What do I need to control?',
 'Focus your will and move forward with determination.',
 ARRAY['What am I fighting for?', 'Where do I need more discipline?', 'What obstacles can I overcome?'],
 'I am focused, determined, and victorious.',
 '{"love": "Taking action, moving relationship forward", "career": "Success through determination, business travel", "health": "Physical strength, overcoming health challenges"}',
 'Cancer season, rapid progress',
 'yes'),

('Strength', 'strength', 'major', NULL, 8, 8,
 ARRAY['strength', 'courage', 'patience', 'control', 'compassion'],
 'Strength, courage, patience, control, and compassion. Inner strength and resilience.',
 'Self-doubt, lack of confidence, inability to control.',
 'Strength represents inner strength, courage, compassion, and the power of gentle control.',
 'A woman gently closes a lion''s mouth, showing that true strength is gentle and comes from within. The infinity symbol above her head represents unlimited inner power.',
 'Eight represents power, material success, and infinite inner strength.',
 'The Gentle Warrior',
 'True strength is gentle and compassionate.',
 'Your inner strength is greater than any external challenge.',
 'Where am I being too forceful? Where do I need more courage?',
 'Use gentle strength and compassionate courage.',
 ARRAY['Where do I need to be stronger?', 'How can I be more gentle with myself?', 'What fears need courage?'],
 'I am strong, courageous, and compassionate.',
 '{"love": "Patience, gentle strength, taming passions", "career": "Handling difficult situations with grace", "health": "Recovery, emotional resilience, stress management"}',
 'Leo season, gradual progress',
 'yes'),

('The Hermit', 'the-hermit', 'major', NULL, 9, 9,
 ARRAY['soul searching', 'introspection', 'solitude', 'inner guidance'],
 'Soul searching, introspection, solitude, and inner guidance. Seeking truth within.',
 'Isolation, loneliness, withdrawal from others.',
 'The Hermit represents introspection, solitude, inner guidance, and the search for truth.',
 'An old man stands alone on a mountain peak, holding a lantern that lights his way. The star in the lantern represents divine wisdom illuminating the path.',
 'Nine represents completion, wisdom, and the hermit''s solitary journey.',
 'The Sage, The Seeker',
 'Wisdom comes from within through solitude and reflection.',
 'Sometimes you must withdraw to find your light.',
 'What am I avoiding through isolation? What wisdom am I seeking?',
 'Go within and seek your inner truth.',
 ARRAY['What truth am I seeking?', 'What do I need solitude for?', 'What wisdom lies within me?'],
 'I find wisdom in solitude and reflection.',
 '{"love": "Need for alone time, soul searching", "career": "Independent work, mentorship, teaching", "health": "Mental health focus, meditation, rest"}',
 'Virgo season, indefinite',
 'maybe'),

('Wheel of Fortune', 'wheel-of-fortune', 'major', NULL, 10, 10,
 ARRAY['good luck', 'karma', 'life cycles', 'destiny', 'turning point'],
 'Good luck, karma, life cycles, destiny, and turning point. Change and fate.',
 'Bad luck, resistance to change, breaking cycles.',
 'The Wheel of Fortune represents cycles, fate, karma, and the turning points in life.',
 'A giant wheel turns in the sky, with various figures rising and falling. The four fixed signs in the corners represent the stability within change.',
 'Ten represents completion of a cycle and the beginning of a new one.',
 'The Fated One',
 'Life is cyclical - what goes up must come down, and vice versa.',
 'Surrender to the wheel of fate and trust the cycles.',
 'What cycle am I resisting? What karma am I creating?',
 'Trust in the turning of the wheel and go with the flow.',
 ARRAY['What cycle is completing?', 'What is my karma teaching me?', 'How can I embrace change?'],
 'I trust in the cycles of life.',
 '{"love": "Fated meeting, relationship turning point", "career": "Career change, destiny calling", "health": "Cycles of health, unexpected recovery"}',
 'Unexpected, Jupiter timing',
 'yes'),

('Justice', 'justice', 'major', NULL, 11, 11,
 ARRAY['justice', 'fairness', 'truth', 'cause and effect', 'law'],
 'Justice, fairness, truth, cause and effect, and law. Accountability and balance.',
 'Unfairness, lack of accountability, dishonesty.',
 'Justice represents fairness, truth, cause and effect, and the law of karma.',
 'A figure sits on a throne holding scales in one hand and a sword in the other, representing balanced judgment and truth.',
 'Eleven represents mastery, intuition, and the balance of justice.',
 'The Judge',
 'Truth and fairness will prevail - be accountable.',
 'You will reap what you sow.',
 'Where am I being unfair? What truth am I avoiding?',
 'Seek truth, be fair, and take responsibility.',
 ARRAY['What needs to be balanced?', 'Am I being fair?', 'What truth needs to be told?'],
 'I seek truth and act with fairness.',
 '{"love": "Fairness in relationship, legal matters", "career": "Legal issues, contracts, fair treatment", "health": "Balance needed, medical diagnoses"}',
 'Libra season, legal timing',
 'yes'),

('The Hanged Man', 'the-hanged-man', 'major', NULL, 12, 12,
 ARRAY['pause', 'surrender', 'letting go', 'new perspective'],
 'Pause, surrender, letting go, and new perspective. Willing sacrifice.',
 'Delays, resistance, stalling, indecision.',
 'The Hanged Man represents surrender, letting go, and seeing things from a new perspective.',
 'A man hangs upside down from a tree, yet his face is peaceful. His new perspective allows him to see what he couldn''t before.',
 'Twelve represents sacrifice, surrender, and a higher perspective.',
 'The Martyr, The Surrendered',
 'Sometimes you must let go to move forward.',
 'A new perspective comes from surrendering control.',
 'What am I resisting? What perspective am I clinging to?',
 'Let go and allow a new perspective to emerge.',
 ARRAY['What do I need to release?', 'What new perspective is available?', 'Where am I resisting surrender?'],
 'I surrender and allow new perspectives.',
 '{"love": "Waiting period, sacrifice for relationship", "career": "Pause in career, need for new approach", "health": "Rest required, changing perspective on health"}',
 'Indefinite waiting, Neptune timing',
 'no'),

('Death', 'death', 'major', NULL, 13, 13,
 ARRAY['endings', 'change', 'transformation', 'transition'],
 'Endings, change, transformation, and transition. Necessary endings for new beginnings.',
 'Resistance to change, inability to let go.',
 'Death represents endings, transformation, and the necessary release that allows new growth.',
 'A skeleton in armor rides a white horse, representing the inevitability of endings. The rising sun in the background promises rebirth.',
 'Thirteen represents transformation, death and rebirth, and profound change.',
 'The Transformer',
 'Endings are necessary for new beginnings.',
 'Let go of what no longer serves you.',
 'What am I afraid to release? What transformation am I resisting?',
 'Embrace endings and trust in transformation.',
 ARRAY['What needs to end?', 'What transformation is calling?', 'What am I afraid to let go of?'],
 'I embrace change and transformation.',
 '{"love": "Relationship ending or transforming", "career": "Job ending, career transformation", "health": "Major health changes, recovery"}',
 'Scorpio season, major life transitions',
 'no'),

('Temperance', 'temperance', 'major', NULL, 14, 14,
 ARRAY['balance', 'moderation', 'patience', 'purpose', 'meaning'],
 'Balance, moderation, patience, purpose, and meaning. Alchemy and integration.',
 'Imbalance, excess, lack of long-term vision.',
 'Temperance represents balance, moderation, patience, and the alchemical process of integration.',
 'An angel pours water between two cups, representing the flow and balance of energies. One foot on land and one in water shows balance between worlds.',
 'Fourteen represents balance, temperance, and alchemical transformation.',
 'The Alchemist',
 'Balance and moderation create harmony.',
 'Patience and purpose create meaning.',
 'Where am I out of balance? What needs integrating?',
 'Practice moderation and seek balance.',
 ARRAY['Where do I need more balance?', 'What is my higher purpose?', 'How can I integrate opposing forces?'],
 'I am balanced, patient, and purposeful.',
 '{"love": "Harmony, partnership balance, patience", "career": "Teamwork, balanced approach, patience pays off", "health": "Moderation, holistic health, recovery"}',
 'Sagittarius season, gradual progress',
 'yes'),

('The Devil', 'the-devil', 'major', NULL, 15, 15,
 ARRAY['shadow self', 'attachment', 'addiction', 'restriction', 'sexuality'],
 'Shadow self, attachment, addiction, restriction, and sexuality. Bondage to materialism.',
 'Releasing limiting beliefs, exploring dark thoughts, detachment.',
 'The Devil represents bondage, addiction, sexuality, and the shadow aspects we must face.',
 'Two naked figures are chained to the devil''s throne, but the chains are loose - they could remove them at any time. This represents willing bondage to materialism or addiction.',
 'Fifteen represents material bondage, shadow work, and the power we give to fear.',
 'The Shadow, The Tempter',
 'You are only as bound as you believe you are.',
 'Face your shadow to reclaim your power.',
 'What am I enslaved to? What shadow aspects am I denying?',
 'Examine your attachments and reclaim your power.',
 ARRAY['What am I attached to?', 'What shadow needs integration?', 'Where am I giving away my power?'],
 'I face my shadow and reclaim my power.',
 '{"love": "Codependency, sexual issues, toxic patterns", "career": "Unhealthy work patterns, materialism", "health": "Addiction, mental health, shadow work needed"}',
 'Capricorn season, immediate',
 'no'),

('The Tower', 'the-tower', 'major', NULL, 16, 16,
 ARRAY['sudden change', 'upheaval', 'chaos', 'revelation', 'awakening'],
 'Sudden change, upheaval, chaos, revelation, and awakening. Necessary destruction.',
 'Personal transformation, fear of change, averting disaster.',
 'The Tower represents sudden upheaval, chaos, revelation, and the destruction of false structures.',
 'Lightning strikes a tower, causing it to crumble. Figures fall from the tower, representing the collapse of false beliefs and structures.',
 'Sixteen represents the destruction that clears the way for truth.',
 'The Destroyer',
 'Sometimes structures must fall for truth to be revealed.',
 'What looks like destruction is actually liberation.',
 'What false structure am I clinging to? What truth am I avoiding?',
 'Allow false structures to fall and embrace revelation.',
 ARRAY['What needs to be destroyed?', 'What truth is being revealed?', 'What am I building on false foundations?'],
 'I release what no longer serves and embrace truth.',
 '{"love": "Relationship upheaval, truth revealed", "career": "Job loss, career upheaval, sudden change", "health": "Health crisis, sudden illness, awakening"}',
 'Sudden, unexpected',
 'no'),

('The Star', 'the-star', 'major', NULL, 17, 17,
 ARRAY['hope', 'faith', 'purpose', 'renewal', 'spirituality'],
 'Hope, faith, purpose, renewal, and spirituality. Healing and inspiration.',
 'Lack of faith, despair, self-trust, disconnection.',
 'The Star represents hope, faith, renewal, and spiritual connection after the storm.',
 'A naked woman kneels by water, pouring from two jugs - one into water, one onto land. Eight stars shine above, representing hope and divine connection.',
 'Seventeen represents hope, faith, and spiritual renewal.',
 'The Hopeful One',
 'After the storm comes the star of hope.',
 'You are divinely guided and protected.',
 'Where have I lost hope? What is my spiritual calling?',
 'Have faith and trust in divine guidance.',
 ARRAY['What gives me hope?', 'What is my spiritual purpose?', 'How can I renew my faith?'],
 'I am hopeful, faithful, and divinely guided.',
 '{"love": "Healing in love, spiritual connection", "career": "Renewed inspiration, spiritual work", "health": "Healing, recovery, spiritual health"}',
 'Aquarius season, long-term',
 'yes'),

('The Moon', 'the-moon', 'major', NULL, 18, 18,
 ARRAY['illusion', 'fear', 'anxiety', 'subconscious', 'intuition'],
 'Illusion, fear, anxiety, subconscious, and intuition. The shadow realm.',
 'Release of fear, repressed emotion, inner confusion.',
 'The Moon represents illusion, fear, the subconscious, and the mysteries of the night.',
 'A full moon shines over a path between two towers. A dog and wolf howl at the moon, and a crayfish emerges from the water, representing the emergence of the subconscious.',
 'Eighteen represents illusion, intuition, and the mysteries of the subconscious.',
 'The Dreamer',
 'Not everything is as it seems - trust your intuition.',
 'Your fears are illusions created by your mind.',
 'What am I afraid of? What illusion am I believing?',
 'Navigate the illusions with intuition and trust.',
 ARRAY['What fears need facing?', 'What is real vs. illusion?', 'What is my subconscious revealing?'],
 'I trust my intuition through uncertainty.',
 '{"love": "Confusion, illusions, hidden truths", "career": "Uncertainty, hidden information", "health": "Anxiety, sleep issues, mental health"}',
 'Pisces season, full moon',
 'unclear'),

('The Sun', 'the-sun', 'major', NULL, 19, 19,
 ARRAY['positivity', 'fun', 'warmth', 'success', 'vitality'],
 'Positivity, fun, warmth, success, and vitality. Joy and celebration.',
 'Inner child, feeling down, overly optimistic.',
 'The Sun represents success, joy, celebration, vitality, and the light of consciousness.',
 'A child rides a white horse under a bright sun, representing innocence, joy, and successful completion. Sunflowers represent life and vitality.',
 'Nineteen represents completion, joy, and the fullness of life.',
 'The Child',
 'Joy is your natural state - embrace it.',
 'Success and happiness are your birthright.',
 'Where have I lost my joy? What shadows need light?',
 'Embrace joy and celebrate life.',
 ARRAY['What brings me joy?', 'How can I be more playful?', 'What success should I celebrate?'],
 'I am joyful, successful, and full of vitality.',
 '{"love": "Joy, warmth, successful relationship", "career": "Success, recognition, achievement", "health": "Vitality, energy, good health"}',
 'Summer, Leo season',
 'yes'),

('Judgement', 'judgement', 'major', NULL, 20, 20,
 ARRAY['judgement', 'rebirth', 'inner calling', 'absolution'],
 'Judgement, rebirth, inner calling, and absolution. Self-evaluation and transformation.',
 'Self-doubt, inner critic, ignoring the call.',
 'Judgement represents rebirth, renewal, self-evaluation, and answering your inner calling.',
 'An angel blows a trumpet, calling souls to rise from their graves for final judgment. This represents spiritual awakening and rebirth.',
 'Twenty represents completion, judgment, and the final reckoning.',
 'The Reborn',
 'It''s time to answer your higher calling.',
 'Release judgment of yourself and others.',
 'What am I judging? What calling am I ignoring?',
 'Evaluate yourself fairly and answer your calling.',
 ARRAY['What is my calling?', 'What needs forgiving?', 'How have I grown?'],
 'I answer my calling and embrace rebirth.',
 '{"love": "Relationship resurrection, forgiveness", "career": "Career calling, major decision", "health": "Recovery, transformation, renewal"}',
 'Pluto timing, major life review',
 'yes'),

('The World', 'the-world', 'major', NULL, 21, 21,
 ARRAY['completion', 'accomplishment', 'travel', 'fulfillment'],
 'Completion, accomplishment, travel, and fulfillment. The end of a cycle.',
 'Seeking closure, incomplete goals, lack of completion.',
 'The World represents completion, accomplishment, the end of a cycle, and cosmic consciousness.',
 'A naked figure dances within a wreath, representing completion and wholeness. The four fixed signs in the corners represent mastery of all elements.',
 'Twenty-one represents completion, mastery, and cosmic consciousness.',
 'The Whole One',
 'You have completed the journey and achieved wholeness.',
 'The end is a new beginning.',
 'What am I resisting completing? What cycle is ending?',
 'Celebrate completion and prepare for a new cycle.',
 ARRAY['What have I accomplished?', 'What cycle is completing?', 'What new journey awaits?'],
 'I am whole, complete, and accomplished.',
 '{"love": "Relationship fulfillment, soulmate connection", "career": "Goal achievement, success, recognition", "health": "Complete healing, wellness achieved"}',
 'Saturn return, completion',
 'yes');

-- =============================================================================
-- MINOR ARCANA - WANDS (14 cards)
-- =============================================================================
-- Fire element, passion, creativity, action, willpower

INSERT INTO tarot_cards (name, slug, card_type, suit, number, keywords, upright_meaning, reversed_meaning, description, advice, love_career_health, timing, yes_no) VALUES
('Ace of Wands', 'ace-of-wands', 'minor', 'wands', 1,
 ARRAY['inspiration', 'new opportunities', 'growth', 'potential'],
 'A new spark of inspiration, creative energy, and potential. New beginnings in passion and action.',
 'Emerging ideas, lack of direction, distractions, delays.',
 'The Ace of Wands represents a burst of creative energy, inspiration, and the spark of a new beginning in passion, career, or creative projects.',
 'Seize new opportunities and act on your inspiration.',
 '{"love": "New passionate romance, exciting beginning", "career": "New job opportunity, creative project", "health": "Energy boost, new health routine"}',
 'Spring, immediate action',
 'yes'),

('Two of Wands', 'two-of-wands', 'minor', 'wands', 2,
 ARRAY['planning', 'future planning', 'progress', 'decisions'],
 'Planning for the future, making decisions, and contemplating the next steps.',
 'Fear of unknown, lack of planning, bad planning.',
 'The Two of Wands shows someone looking out from their position of power, planning their next move and considering future possibilities.',
 'Plan carefully but don''t be afraid to take the leap.',
 '{"love": "Planning future together, decisions ahead", "career": "Business planning, expansion decisions", "health": "Planning health goals"}',
 '2-3 months',
 'yes'),

('Three of Wands', 'three-of-wands', 'minor', 'wands', 3,
 ARRAY['expansion', 'foresight', 'overseas opportunities', 'progress'],
 'Progress, expansion, foresight, and anticipating future success.',
 'Obstacles, delays, frustration, lack of foresight.',
 'The Three of Wands depicts someone looking out at the horizon, watching their ships come in - progress is being made and expansion is happening.',
 'Your plans are manifesting - keep the vision.',
 '{"love": "Long-distance relationship, expansion", "career": "Business expansion, international opportunities", "health": "Progress in health goals"}',
 '3-6 months',
 'yes'),

('Four of Wands', 'four-of-wands', 'minor', 'wands', 4,
 ARRAY['celebration', 'harmony', 'marriage', 'home', 'community'],
 'Celebration, harmony, marriage, homecoming, and community gatherings.',
 'Home conflicts, lack of harmony, canceled celebrations.',
 'The Four of Wands shows a joyous celebration under a canopy of flowers - a time of harmony, celebration, and community.',
 'Celebrate your achievements and enjoy the moment.',
 '{"love": "Engagement, wedding, relationship milestone", "career": "Work celebration, team harmony", "health": "Stability, wellness celebration"}',
 'Summer, Aries season',
 'yes'),

('Five of Wands', 'five-of-wands', 'minor', 'wands', 5,
 ARRAY['conflict', 'disagreements', 'competition', 'tension'],
 'Conflict, competition, disagreements, and tension. Healthy competition.',
 'Inner conflict, avoiding conflict, resolution.',
 'The Five of Wands depicts five people in chaotic conflict or competition - everyone fighting for their own position.',
 'Navigate conflicts constructively and pick your battles.',
 '{"love": "Arguments, tension, communication issues", "career": "Competition, office politics, conflict", "health": "Stress, inflammation, tension"}',
 'Short-term conflict',
 'no'),

('Six of Wands', 'six-of-wands', 'minor', 'wands', 6,
 ARRAY['success', 'public recognition', 'progress', 'victory'],
 'Success, public recognition, progress, and victory. Triumph and acclaim.',
 'Private achievement, self-doubt, egotism, lack of recognition.',
 'The Six of Wands shows a victorious figure on horseback, being celebrated by others - success and public recognition.',
 'Accept recognition with humility and gratitude.',
 '{"love": "Being admired, public relationship", "career": "Promotion, recognition, achievement", "health": "Recovery success, fitness goals met"}',
 'Leo season, immediate',
 'yes'),

('Seven of Wands', 'seven-of-wands', 'minor', 'wands', 7,
 ARRAY['perseverance', 'defensive', 'maintaining position', 'challenge'],
 'Perseverance, defending your position, standing your ground despite challenges.',
 'Giving up, overwhelmed, not standing your ground.',
 'The Seven of Wands depicts someone defending their position against multiple opponents - standing firm despite challenges.',
 'Stand your ground but choose your battles wisely.',
 '{"love": "Defending relationship, rivals", "career": "Competition, defending position", "health": "Fighting illness, perseverance"}',
 'Ongoing challenge',
 'yes'),

('Eight of Wands', 'eight-of-wands', 'minor', 'wands', 8,
 ARRAY['speed', 'action', 'air travel', 'swift change'],
 'Speed, rapid action, air travel, and swift change. Things moving quickly.',
 'Delays, frustration, resisting change, slowing down.',
 'The Eight of Wands shows eight wands flying through the air - rapid movement, swift communication, and fast-paced change.',
 'Move quickly and seize the momentum.',
 '{"love": "Fast-moving romance, messages", "career": "Rapid progress, travel, communication", "health": "Quick recovery, energy surge"}',
 'Very soon, days',
 'yes'),

('Nine of Wands', 'nine-of-wands', 'minor', 'wands', 9,
 ARRAY['resilience', 'persistence', 'last stand', 'boundaries'],
 'Resilience, persistence, testing your limits, and defending boundaries.',
 'Exhaustion, giving up, paranoia, inability to trust.',
 'The Nine of Wands shows a wounded warrior still standing, ready to defend - resilience despite weariness.',
 'You''re almost there - don''t give up now.',
 '{"love": "Relationship challenges, guarded heart", "career": "Near completion, pushing through", "health": "Fatigue, need boundaries"}',
 'Final stretch',
 'yes'),

('Ten of Wands', 'ten-of-wands', 'minor', 'wands', 10,
 ARRAY['burden', 'responsibility', 'hard work', 'stress'],
 'Burden, responsibility, hard work, and stress. Carrying too much.',
 'Doing it all, release, delegation, priorities.',
 'The Ten of Wands depicts someone carrying a heavy burden of ten wands - overwhelm and excessive responsibility.',
 'Delegate, prioritize, and release what''s not yours.',
 '{"love": "Relationship burden, responsibilities", "career": "Overwhelm, too much work, burnout", "health": "Stress, exhaustion, back pain"}',
 'Temporary burden',
 'no'),

('Page of Wands', 'page-of-wands', 'minor', 'wands', NULL,
 ARRAY['inspiration', 'ideas', 'discovery', 'free spirit'],
 'Inspiration, new ideas, discovery, and free-spirited energy. Enthusiasm.',
 'Lack of direction, procrastination, creating conflict.',
 'The Page of Wands represents youthful enthusiasm, new ideas, and the spark of creative inspiration.',
 'Explore your passions and follow your curiosity.',
 '{"love": "Flirtation, playful energy, new spark", "career": "New ideas, creative projects, exploration", "health": "Trying new activities, playful exercise"}',
 'Youthful timing, Aries/Leo/Sagittarius',
 'yes'),

('Knight of Wands', 'knight-of-wands', 'minor', 'wands', NULL,
 ARRAY['energy', 'passion', 'adventure', 'impulsiveness'],
 'Energy, passion, adventure, and impulsive action. Fearless pursuit.',
 'Recklessness, impatience, unfinished business, scattered energy.',
 'The Knight of Wands is the bold adventurer, charging forward with passion and fearless energy.',
 'Channel your passion but don''t be reckless.',
 '{"love": "Passionate romance, adventurous lover", "career": "Bold moves, taking risks, travel", "health": "High energy, active lifestyle"}',
 'Immediate, fire sign energy',
 'yes'),

('Queen of Wands', 'queen-of-wands', 'minor', 'wands', NULL,
 ARRAY['courage', 'confidence', 'independence', 'determination'],
 'Courage, confidence, independence, and passionate determination. Magnetic energy.',
 'Selfishness, jealousy, insecurity, temperamental.',
 'The Queen of Wands is confident, passionate, determined, and magnetic - she knows her worth and radiates power.',
 'Own your power and lead with confidence.',
 '{"love": "Confident partner, passionate relationship", "career": "Leadership, entrepreneurship, influence", "health": "Vitality, confidence, active"}',
 'Fire sign person or energy',
 'yes'),

('King of Wands', 'king-of-wands', 'minor', 'wands', NULL,
 ARRAY['leadership', 'vision', 'entrepreneur', 'honor'],
 'Leadership, vision, entrepreneurship, and natural-born leader energy.',
 'Impulsiveness, ruthlessness, high expectations, arrogance.',
 'The King of Wands is the visionary leader and entrepreneur who inspires others with natural charisma and bold vision.',
 'Lead with vision but remain humble.',
 '{"love": "Strong partner, passionate leader", "career": "CEO energy, entrepreneurship, leadership", "health": "Strong vitality, active leadership"}',
 'Fire sign person, mature energy',
 'yes');

-- =============================================================================
-- MINOR ARCANA - CUPS (14 cards)
-- =============================================================================
-- Water element, emotions, relationships, intuition

INSERT INTO tarot_cards (name, slug, card_type, suit, number, keywords, upright_meaning, reversed_meaning, description, advice, love_career_health, timing, yes_no) VALUES
('Ace of Cups', 'ace-of-cups', 'minor', 'cups', 1,
 ARRAY['new love', 'emotional awakening', 'creativity', 'spirituality'],
 'New love, emotional awakening, creative expression, and spiritual connection.',
 'Emotional loss, blocked creativity, emptiness, sadness.',
 'The Ace of Cups represents the overflowing of emotions, new love, spiritual awakening, and creative inspiration.',
 'Open your heart to new emotional experiences.',
 '{"love": "New romance, deep connection, proposal", "career": "Creative inspiration, emotional fulfillment", "health": "Emotional healing, self-love"}',
 'New moon, spring',
 'yes'),

('Two of Cups', 'two-of-cups', 'minor', 'cups', 2,
 ARRAY['partnership', 'unity', 'love', 'attraction'],
 'Partnership, unity, love, and mutual attraction. Balanced relationships.',
 'Imbalance, broken relationship, disharmony, mistrust.',
 'The Two of Cups shows two people in harmonious partnership, exchanging cups in mutual respect and love.',
 'Build balanced, respectful partnerships.',
 '{"love": "Soulmate connection, engagement, harmony", "career": "Partnership, collaboration, teamwork", "health": "Healing partnership, balance"}',
 'Cancer/Scorpio/Pisces, Venus in Cancer',
 'yes'),

('Three of Cups', 'three-of-cups', 'minor', 'cups', 3,
 ARRAY['celebration', 'friendship', 'creativity', 'community'],
 'Celebration, friendship, creativity, and community. Joyful gatherings.',
 'Overindulgence, isolation, loneliness, withdrawal.',
 'The Three of Cups depicts three women celebrating together - friendship, community, and joyful celebration.',
 'Celebrate with loved ones and nurture friendships.',
 '{"love": "Social romance, celebration, friends", "career": "Team success, networking, collaboration", "health": "Social wellness, celebration"}',
 'Summer, Mercury in Cancer',
 'yes'),

('Four of Cups', 'four-of-cups', 'minor', 'cups', 4,
 ARRAY['apathy', 'contemplation', 'reevaluation', 'meditation'],
 'Apathy, contemplation, reevaluation, and meditation. Looking inward.',
 'Awareness, acceptance, moving on, new perspective.',
 'The Four of Cups shows someone sitting under a tree, contemplating three cups while a fourth is offered - introspection and apathy.',
 'Look within but don''t miss new opportunities.',
 '{"love": "Taking love for granted, boredom", "career": "Job dissatisfaction, contemplation", "health": "Depression, need for reflection"}',
 'Moon in Cancer, contemplation period',
 'no'),

('Five of Cups', 'five-of-cups', 'minor', 'cups', 5,
 ARRAY['loss', 'grief', 'disappointment', 'regret'],
 'Loss, grief, disappointment, and regret. Focusing on what''s lost.',
 'Acceptance, moving on, forgiveness, healing.',
 'The Five of Cups depicts someone mourning spilled cups, not seeing the two cups still standing behind them.',
 'Acknowledge loss but don''t miss what remains.',
 '{"love": "Heartbreak, loss, mourning", "career": "Disappointment, loss, regret", "health": "Grief, emotional pain"}',
 'Mars in Scorpio, grieving period',
 'no'),

('Six of Cups', 'six-of-cups', 'minor', 'cups', 6,
 ARRAY['nostalgia', 'memories', 'childhood', 'innocence'],
 'Nostalgia, memories, childhood, and innocence. Revisiting the past.',
 'Stuck in past, unrealistic expectations, leaving home.',
 'The Six of Cups shows children exchanging flowers - nostalgia, innocence, and happy memories from the past.',
 'Honor the past but live in the present.',
 '{"love": "Past love returning, childhood sweethearts", "career": "Previous job, nostalgia, reunion", "health": "Healing childhood wounds"}',
 'Sun in Scorpio, past timing',
 'maybe'),

('Seven of Cups', 'seven-of-cups', 'minor', 'cups', 7,
 ARRAY['choices', 'illusion', 'fantasy', 'wishful thinking'],
 'Choices, illusion, fantasy, and wishful thinking. Many options.',
 'Clarity, values alignment, making choices, disillusionment.',
 'The Seven of Cups shows seven cups floating in clouds with different visions - choices, illusions, and possibilities.',
 'Choose wisely and discern reality from fantasy.',
 '{"love": "Fantasy vs reality, many options", "career": "Too many options, unrealistic goals", "health": "Confusion, illusions about health"}',
 'Venus in Scorpio, uncertain',
 'unclear'),

('Eight of Cups', 'eight-of-cups', 'minor', 'cups', 8,
 ARRAY['walking away', 'disillusionment', 'abandonment', 'withdrawal'],
 'Walking away, disillusionment, leaving behind what no longer serves.',
 'Avoidance, fear of change, fear of loss, staying stuck.',
 'The Eight of Cups depicts someone walking away from eight stacked cups toward the mountains - leaving for soul-searching.',
 'Sometimes walking away is the bravest choice.',
 '{"love": "Leaving relationship, moving on", "career": "Quitting job, career change", "health": "Leaving unhealthy habits"}',
 'Saturn in Pisces, transition time',
 'yes'),

('Nine of Cups', 'nine-of-cups', 'minor', 'cups', 9,
 ARRAY['wish fulfillment', 'satisfaction', 'contentment', 'luxury'],
 'Wish fulfillment, satisfaction, contentment, and luxury. The wish card.',
 'Inner happiness, materialism, dissatisfaction, greed.',
 'The Nine of Cups shows a satisfied figure sitting before nine cups - wishes fulfilled and contentment achieved.',
 'Enjoy your success but share your abundance.',
 '{"love": "Relationship satisfaction, wishes granted", "career": "Success, satisfaction, rewards", "health": "Good health, wellness achieved"}',
 'Jupiter in Pisces, wish timing',
 'yes'),

('Ten of Cups', 'ten-of-cups', 'minor', 'cups', 10,
 ARRAY['happiness', 'family', 'harmony', 'alignment'],
 'Happiness, family harmony, emotional fulfillment, and alignment.',
 'Disconnection, values not aligned, broken family.',
 'The Ten of Cups shows a happy family under a rainbow of ten cups - ultimate emotional fulfillment and harmony.',
 'Cherish your relationships and celebrate harmony.',
 '{"love": "Marriage, family bliss, soulmate", "career": "Work-life balance, team harmony", "health": "Emotional wellness, family health"}',
 'Mars in Pisces, long-term',
 'yes'),

('Page of Cups', 'page-of-cups', 'minor', 'cups', NULL,
 ARRAY['creative opportunities', 'intuition', 'sensitivity', 'inner child'],
 'Creative opportunities, intuitive messages, curiosity, and youthful emotion.',
 'Emotional immaturity, insecurity, disappointment.',
 'The Page of Cups represents creative opportunities, intuitive messages, and the emotional exploration of the inner child.',
 'Trust your intuition and embrace creativity.',
 '{"love": "New romance, sweet messages, sensitivity", "career": "Creative opportunities, intuitive work", "health": "Emotional awareness, intuitive healing"}',
 'Water sign energy, youthful',
 'yes'),

('Knight of Cups', 'knight-of-cups', 'minor', 'cups', NULL,
 ARRAY['romance', 'charm', 'imagination', 'beauty'],
 'Romance, charm, following your heart, and creative pursuit.',
 'Moodiness, disappointment, unrealistic expectations.',
 'The Knight of Cups is the romantic dreamer, offering a cup with heartfelt sincerity and creative imagination.',
 'Follow your heart but stay grounded.',
 '{"love": "Romantic proposal, charming suitor", "career": "Creative pursuit, artistic work", "health": "Emotional healing, creative therapy"}',
 'Pisces energy, romantic timing',
 'yes'),

('Queen of Cups', 'queen-of-cups', 'minor', 'cups', NULL,
 ARRAY['compassion', 'calm', 'comfort', 'intuitive'],
 'Compassion, calm, emotional security, and intuitive wisdom.',
 'Insecurity, giving too much, needy, fragile.',
 'The Queen of Cups is emotionally mature, compassionate, intuitive, and nurturing - the emotional caregiver.',
 'Lead with compassion and trust your intuition.',
 '{"love": "Nurturing partner, emotional depth", "career": "Counseling, healing work, intuitive", "health": "Emotional wellness, intuitive healing"}',
 'Cancer energy, maternal',
 'yes'),

('King of Cups', 'king-of-cups', 'minor', 'cups', NULL,
 ARRAY['emotional balance', 'control', 'generosity', 'wisdom'],
 'Emotional balance, diplomatic, compassionate, and emotionally mature.',
 'Coldness, moodiness, manipulation, emotional control.',
 'The King of Cups is emotionally balanced, compassionate, and wise - mastery over emotions without suppression.',
 'Balance emotion with wisdom and compassion.',
 '{"love": "Emotionally mature partner, balance", "career": "Wise leadership, emotional intelligence", "health": "Emotional balance, wellness mastery"}',
 'Scorpio energy, mature',
 'yes');

-- =============================================================================
-- MINOR ARCANA - SWORDS (14 cards)
-- =============================================================================
-- Air element, thoughts, words, intellect, truth

INSERT INTO tarot_cards (name, slug, card_type, suit, number, keywords, upright_meaning, reversed_meaning, description, advice, love_career_health, timing, yes_no) VALUES
('Ace of Swords', 'ace-of-swords', 'minor', 'swords', 1,
 ARRAY['breakthrough', 'clarity', 'truth', 'new ideas'],
 'Breakthrough, clarity, sharp mind, truth revealed, and new ideas.',
 'Confusion, chaos, lack of clarity, misinformation.',
 'The Ace of Swords represents mental clarity, breakthrough moments, truth, and the power of the mind.',
 'Seek truth and act on your clarity.',
 '{"love": "Truth revealed, clarity in relationship", "career": "Breakthrough idea, mental clarity", "health": "Mental clarity, diagnosis"}',
 'Immediate, air sign timing',
 'yes'),

('Two of Swords', 'two-of-swords', 'minor', 'swords', 2,
 ARRAY['difficult decisions', 'stalemate', 'avoidance', 'denial'],
 'Difficult decisions, stalemate, weighing options, and avoidance.',
 'Indecision, confusion, information overload, no right choice.',
 'The Two of Swords depicts a blindfolded figure holding two swords - indecision, stalemate, and avoided choices.',
 'Remove the blindfold and make a decision.',
 '{"love": "Relationship crossroads, avoidance", "career": "Difficult choice, stalemate", "health": "Denial, need for decision"}',
 'Moon in Libra, delayed',
 'no'),

('Three of Swords', 'three-of-swords', 'minor', 'swords', 3,
 ARRAY['heartbreak', 'grief', 'pain', 'betrayal'],
 'Heartbreak, emotional pain, sorrow, grief, and painful truth.',
 'Recovery, forgiveness, moving on, healing.',
 'The Three of Swords shows three swords piercing a heart - deep emotional pain, heartbreak, and painful truth.',
 'Allow yourself to grieve and then heal.',
 '{"love": "Heartbreak, betrayal, separation", "career": "Painful loss, betrayal, conflict", "health": "Emotional pain, heart issues"}',
 'Saturn in Libra, painful period',
 'no'),

('Four of Swords', 'four-of-swords', 'minor', 'swords', 4,
 ARRAY['rest', 'recovery', 'contemplation', 'recuperation'],
 'Rest, recovery, meditation, contemplation, and taking a break.',
 'Exhaustion, burnout, stagnation, restlessness.',
 'The Four of Swords shows a figure resting on a tomb - necessary rest, recovery, and contemplation.',
 'Rest and recharge before moving forward.',
 '{"love": "Taking break, rest from drama", "career": "Vacation, sabbatical, rest", "health": "Recovery, rest needed, meditation"}',
 'Jupiter in Libra, rest period',
 'no'),

('Five of Swords', 'five-of-swords', 'minor', 'swords', 5,
 ARRAY['conflict', 'defeat', 'winning at all costs', 'betrayal'],
 'Conflict, tension, loss, defeat, and winning at all costs.',
 'Reconciliation, resolution, moving on, forgiveness.',
 'The Five of Swords depicts a figure gathering swords while others walk away defeated - hollow victory and conflict.',
 'Choose battles wisely - some victories aren''t worth it.',
 '{"love": "Arguments, betrayal, hostility", "career": "Office politics, conflict, hollow victory", "health": "Stress, conflict affecting health"}',
 'Venus in Aquarius, conflict time',
 'no'),

('Six of Swords', 'six-of-swords', 'minor', 'swords', 6,
 ARRAY['transition', 'change', 'moving on', 'travel'],
 'Transition, moving on, leaving behind, travel, and gradual change.',
 'Resistance to change, unable to move on, stuck.',
 'The Six of Swords shows figures in a boat moving toward calmer waters - transition and necessary change.',
 'Trust the transition and move toward better waters.',
 '{"love": "Moving on, relationship transition", "career": "Job change, relocation, transition", "health": "Recovery, moving toward healing"}',
 'Mercury in Aquarius, gradual',
 'yes'),

('Seven of Swords', 'seven-of-swords', 'minor', 'swords', 7,
 ARRAY['deception', 'betrayal', 'strategy', 'sneaky'],
 'Deception, betrayal, getting away with something, strategy.',
 'Coming clean, rethinking approach, conscience.',
 'The Seven of Swords depicts someone sneaking away with swords - deception, strategy, or getting away with something.',
 'Be honest and ethical in your approach.',
 '{"love": "Infidelity, deception, secrets", "career": "Office politics, strategic, dishonesty", "health": "Hidden health issues"}',
 'Moon in Aquarius, sneaky timing',
 'no'),

('Eight of Swords', 'eight-of-swords', 'minor', 'swords', 8,
 ARRAY['trapped', 'restricted', 'victim mentality', 'paralyzed'],
 'Feeling trapped, restricted, victim mentality, and self-imposed restrictions.',
 'Self-acceptance, new perspective, freedom, release.',
 'The Eight of Swords shows a bound and blindfolded figure surrounded by swords - feeling trapped by circumstances or thoughts.',
 'The bonds are looser than you think - free yourself.',
 '{"love": "Feeling trapped, victim mindset", "career": "Stuck in job, limited thinking", "health": "Mental prison, anxiety, restrictions"}',
 'Jupiter in Gemini, temporary',
 'no'),

('Nine of Swords', 'nine-of-swords', 'minor', 'swords', 9,
 ARRAY['anxiety', 'worry', 'nightmares', 'fear'],
 'Anxiety, worry, fear, depression, and nightmares. Mental anguish.',
 'Hope, reaching out, despair ending, recovery.',
 'The Nine of Swords depicts someone sitting up in bed in anguish - anxiety, worry, and mental torment.',
 'Your fears are worse than reality - seek support.',
 '{"love": "Anxiety about relationship, fears", "career": "Work anxiety, stress, overwhelm", "health": "Anxiety, insomnia, mental health"}',
 'Mars in Gemini, anxious period',
 'no'),

('Ten of Swords', 'ten-of-swords', 'minor', 'swords', 10,
 ARRAY['painful ending', 'rock bottom', 'betrayal', 'loss'],
 'Painful ending, rock bottom, betrayal, crisis, and hitting bottom.',
 'Recovery, regeneration, fear of ruin, inevitable end.',
 'The Ten of Swords shows a figure with ten swords in their back - rock bottom, painful ending, but also the promise of dawn.',
 'You''ve hit bottom - the only way is up.',
 '{"love": "Relationship ending, betrayal, crisis", "career": "Job loss, failure, rock bottom", "health": "Crisis, but recovery ahead"}',
 'Sun in Gemini, ending',
 'no'),

('Page of Swords', 'page-of-swords', 'minor', 'swords', NULL,
 ARRAY['curiosity', 'restless', 'mental energy', 'vigilance'],
 'Curiosity, new ideas, vigilance, and mental restlessness.',
 'Scatterbrained, cynical, sarcastic, gossipy.',
 'The Page of Swords represents intellectual curiosity, new ideas, vigilance, and youthful mental energy.',
 'Stay curious but be mindful of your words.',
 '{"love": "Mental connection, communication", "career": "New ideas, research, vigilance", "health": "Mental activity, restlessness"}',
 'Air sign energy, youthful',
 'maybe'),

('Knight of Swords', 'knight-of-swords', 'minor', 'swords', NULL,
 ARRAY['action', 'impulsiveness', 'defending beliefs', 'change'],
 'Swift action, impulsiveness, defending beliefs, and rapid change.',
 'Impulsive, reckless, confrontational, all talk.',
 'The Knight of Swords charges forward with single-minded determination - swift action but sometimes reckless.',
 'Act decisively but think before you charge.',
 '{"love": "Sudden change, direct communication", "career": "Rapid action, defending position", "health": "Quick action, impulsive decisions"}',
 'Gemini/Libra/Aquarius, immediate',
 'yes'),

('Queen of Swords', 'queen-of-swords', 'minor', 'swords', NULL,
 ARRAY['independent', 'unbiased', 'clear thinking', 'direct'],
 'Independent, unbiased judgment, clear thinking, and direct communication.',
 'Cold, cruel, bitter, harsh judgment.',
 'The Queen of Swords is intellectually independent, clear-thinking, and direct - she values truth above all.',
 'Think clearly and speak your truth directly.',
 '{"love": "Independence, direct communication", "career": "Clear thinking, unbiased judgment", "health": "Mental clarity, direct approach"}',
 'Libra energy, intellectual',
 'yes'),

('King of Swords', 'king-of-swords', 'minor', 'swords', NULL,
 ARRAY['intellectual', 'authority', 'truth', 'clarity'],
 'Intellectual power, authority, truth, clear thinking, and ethical judgment.',
 'Manipulative, cruel, weakness, coldness.',
 'The King of Swords is the ultimate authority on intellectual power, truth, and clear ethical judgment.',
 'Lead with intellect, truth, and fairness.',
 '{"love": "Intellectual connection, honesty", "career": "Authority, leadership, clear thinking", "health": "Clear diagnosis, mental mastery"}',
 'Aquarius energy, mature authority',
 'yes');

-- =============================================================================
-- MINOR ARCANA - PENTACLES (14 cards)
-- =============================================================================
-- Earth element, material world, finances, career, body

INSERT INTO tarot_cards (name, slug, card_type, suit, number, keywords, upright_meaning, reversed_meaning, description, advice, love_career_health, timing, yes_no) VALUES
('Ace of Pentacles', 'ace-of-pentacles', 'minor', 'pentacles', 1,
 ARRAY['opportunity', 'prosperity', 'new venture', 'manifestation'],
 'New financial opportunity, prosperity, manifestation, and abundance.',
 'Lost opportunity, missed chance, poor financial planning.',
 'The Ace of Pentacles represents a new financial opportunity, material manifestation, and the seed of prosperity.',
 'Seize material opportunities and plant seeds for abundance.',
 '{"love": "Stable relationship, material security", "career": "Job offer, business opportunity, prosperity", "health": "Physical health, body wellness"}',
 'Earth sign timing, winter',
 'yes'),

('Two of Pentacles', 'two-of-pentacles', 'minor', 'pentacles', 2,
 ARRAY['balance', 'adaptability', 'time management', 'priorities'],
 'Balance, multiple priorities, adaptability, and time management.',
 'Imbalance, overwhelm, disorganization, loss of balance.',
 'The Two of Pentacles shows someone juggling two pentacles - balancing multiple priorities and adapting to change.',
 'Stay flexible and prioritize what''s important.',
 '{"love": "Balancing relationship and life", "career": "Juggling projects, multitasking", "health": "Work-life balance needed"}',
 'Jupiter in Capricorn, ongoing',
 'maybe'),

('Three of Pentacles', 'three-of-pentacles', 'minor', 'pentacles', 3,
 ARRAY['teamwork', 'collaboration', 'learning', 'implementation'],
 'Teamwork, collaboration, learning, and skillful implementation.',
 'Working alone, lack of teamwork, poor collaboration.',
 'The Three of Pentacles depicts artisans working together on a cathedral - teamwork, skill, and collaborative success.',
 'Collaborate and value each person''s expertise.',
 '{"love": "Building together, partnership work", "career": "Teamwork, collaboration, recognition", "health": "Team approach, professional help"}',
 'Mars in Capricorn, project timing',
 'yes'),

('Four of Pentacles', 'four-of-pentacles', 'minor', 'pentacles', 4,
 ARRAY['control', 'stability', 'security', 'possessiveness'],
 'Control, financial security, conservatism, and holding on tightly.',
 'Greed, materialism, letting go, giving.',
 'The Four of Pentacles shows someone clutching pentacles tightly - security through control, but also possessiveness.',
 'Find security without becoming possessive.',
 '{"love": "Possessiveness, fear of loss", "career": "Job security, financial control", "health": "Physical tension, holding on"}',
 'Sun in Capricorn, stable',
 'no'),

('Five of Pentacles', 'five-of-pentacles', 'minor', 'pentacles', 5,
 ARRAY['hardship', 'financial loss', 'poverty', 'isolation'],
 'Financial hardship, poverty mentality, isolation, and loss.',
 'Recovery, positive changes, charity, improvement.',
 'The Five of Pentacles shows figures struggling in the cold outside a church - hardship, loss, but help is available.',
 'Seek help - you''re not as alone as you think.',
 '{"love": "Relationship hardship, isolation", "career": "Job loss, financial hardship", "health": "Health issues, lack of resources"}',
 'Mercury in Taurus, difficult period',
 'no'),

('Six of Pentacles', 'six-of-pentacles', 'minor', 'pentacles', 6,
 ARRAY['generosity', 'charity', 'sharing', 'financial harmony'],
 'Generosity, charity, giving and receiving, and financial balance.',
 'Strings attached, inequality, debt, one-sided generosity.',
 'The Six of Pentacles depicts someone giving coins to those in need - generosity, charity, and balanced giving.',
 'Give generously but maintain balance.',
 '{"love": "Generosity in relationship, balance", "career": "Bonus, raise, recognition, charity", "health": "Receiving help, giving support"}',
 'Moon in Taurus, reciprocal',
 'yes'),

('Seven of Pentacles', 'seven-of-pentacles', 'minor', 'pentacles', 7,
 ARRAY['assessment', 'reward', 'patience', 'long-term view'],
 'Long-term view, assessment, perseverance, and waiting for results.',
 'Lack of progress, impatience, limited success.',
 'The Seven of Pentacles shows someone pausing to assess their growing crop - patience, evaluation, and long-term thinking.',
 'Be patient - your efforts will bear fruit.',
 '{"love": "Assessing relationship, patience", "career": "Career assessment, long-term planning", "health": "Long-term health planning"}',
 'Saturn in Taurus, long-term',
 'yes'),

('Eight of Pentacles', 'eight-of-pentacles', 'minor', 'pentacles', 8,
 ARRAY['skill development', 'craftsmanship', 'quality', 'mastery'],
 'Skill development, craftsmanship, hard work, and mastery.',
 'Perfectionism, lack of ambition, low skill, uninspired.',
 'The Eight of Pentacles depicts an artisan focused on crafting pentacles - dedication to skill, quality, and mastery.',
 'Focus on mastery and continuous improvement.',
 '{"love": "Working on relationship, dedication", "career": "Skill building, education, mastery", "health": "Dedicated health routine"}',
 'Sun in Virgo, apprenticeship',
 'yes'),

('Nine of Pentacles', 'nine-of-pentacles', 'minor', 'pentacles', 9,
 ARRAY['abundance', 'luxury', 'self-sufficiency', 'success'],
 'Abundance, luxury, self-sufficiency, and financial independence.',
 'Over-investment in work, hustling, self-worth.',
 'The Nine of Pentacles shows an elegant figure enjoying a luxurious garden - self-made success and independence.',
 'Enjoy your success - you''ve earned it.',
 '{"love": "Independence, self-sufficiency", "career": "Success, financial independence", "health": "Wellness, self-care, luxury"}',
 'Venus in Virgo, harvest time',
 'yes'),

('Ten of Pentacles', 'ten-of-pentacles', 'minor', 'pentacles', 10,
 ARRAY['wealth', 'inheritance', 'family', 'legacy'],
 'Wealth, financial security, family, tradition, and legacy.',
 'Financial failure, loneliness, loss of stability.',
 'The Ten of Pentacles depicts a multi-generational family scene - wealth, legacy, and long-term security.',
 'Build lasting wealth and legacy.',
 '{"love": "Marriage, family, long-term commitment", "career": "Business success, family business, wealth", "health": "Family health, generational wellness"}',
 'Mercury in Virgo, long-term',
 'yes'),

('Page of Pentacles', 'page-of-pentacles', 'minor', 'pentacles', NULL,
 ARRAY['opportunity', 'new job', 'manifestation', 'study'],
 'New opportunity, ambition, diligence, and practical manifestation.',
 'Lack of progress, procrastination, learn from failure.',
 'The Page of Pentacles represents new financial opportunities, scholarly pursuits, and practical beginnings.',
 'Study diligently and seize practical opportunities.',
 '{"love": "Practical romance, building together", "career": "New job, study, apprenticeship", "health": "Starting health routine, education"}',
 'Earth sign energy, beginner',
 'yes'),

('Knight of Pentacles', 'knight-of-pentacles', 'minor', 'pentacles', NULL,
 ARRAY['efficiency', 'routine', 'conservatism', 'methodical'],
 'Hard work, productivity, routine, conservatism, and reliability.',
 'Laziness, obsessiveness, work without reward.',
 'The Knight of Pentacles is the most reliable and hard-working knight - methodical, steady, and committed.',
 'Be steady and reliable in your approach.',
 '{"love": "Stable partner, reliable, committed", "career": "Hard work, reliability, steady progress", "health": "Routine, dedication, slow progress"}',
 'Taurus/Virgo/Capricorn, steady',
 'yes'),

('Queen of Pentacles', 'queen-of-pentacles', 'minor', 'pentacles', NULL,
 ARRAY['practicality', 'creature comforts', 'financial security', 'nurturing'],
 'Practical, nurturing, providing, financial security, and resourcefulness.',
 'Financial independence, self-care, work-life balance.',
 'The Queen of Pentacles is the practical nurturer who creates comfort, security, and abundance for all.',
 'Nurture with practical care and abundance.',
 '{"love": "Nurturing partner, practical love", "career": "Successful businesswoman, practical leadership", "health": "Physical wellness, practical health"}',
 'Capricorn energy, maternal practical',
 'yes'),

('King of Pentacles', 'king-of-pentacles', 'minor', 'pentacles', NULL,
 ARRAY['wealth', 'business', 'leadership', 'security'],
 'Wealth, business success, leadership, discipline, and abundance.',
 'Greed, materialism, wasteful, poor financial management.',
 'The King of Pentacles is the master of the material realm - wealthy, successful, and generous with resources.',
 'Build wealth and lead with abundance.',
 '{"love": "Provider, stable partner, security", "career": "Business success, CEO, wealth", "health": "Physical strength, material wellness"}',
 'Taurus energy, established wealth',
 'yes');

-- Notification
DO $$ 
BEGIN 
    RAISE NOTICE '✓ Complete 78-card tarot deck inserted';
    RAISE NOTICE '  - 22 Major Arcana cards';
    RAISE NOTICE '  - 14 Wands (Fire/Action)';
    RAISE NOTICE '  - 14 Cups (Water/Emotion)';
    RAISE NOTICE '  - 14 Swords (Air/Intellect)';
    RAISE NOTICE '  - 14 Pentacles (Earth/Material)';
END $$;
